# {{projectName}} — MicroPython Firmware
# {{summary}}
# Generated by TheShipboard

{{imports}}

{{sensorSetup}}
{{actuatorSetup}}

{{#if hasWifi}}
import network
wlan = network.WLAN(network.STA_IF)
wlan.active(True)
wlan.connect("{{wifiSsid}}", "YOUR_PASSWORD")
while not wlan.isconnected():
    time.sleep(0.5)
print("WiFi connected:", wlan.ifconfig()[0])
{{/if}}

print("{{projectName}} starting...")

while True:
{{sensorReads}}

{{logicRules}}

    time.sleep({{loopDelay}})
