// {{projectName}} — Automotive Firmware
// {{summary}}
// Generated by TheShipboard

{{configInclude}}
{{includes}}

{{pinDefinitions}}
{{sensorDeclarations}}
{{actuatorDeclarations}}

void setup() {
  Serial.begin(115200);
  Serial.println("{{projectName}} — Automotive init...");
{{sensorInitialization}}
{{actuatorInitialization}}
  Serial.println("Automotive setup complete.");
}

void loop() {
{{sensorReads}}
{{logicRules}}
  delay({{loopDelay}});
}
