// {{projectName}} — Configuration
// Generated by TheShipboard

#ifndef CONFIG_H
#define CONFIG_H

{{pinDefinitions}}

// Loop timing
#define LOOP_DELAY_MS {{loopDelay}}

{{#if hasWifi}}
// WiFi Configuration
#define WIFI_SSID "{{wifiSsid}}"
#define WIFI_PASSWORD "YOUR_PASSWORD"
{{/if}}

{{#if hasMqtt}}
// MQTT Configuration
#define MQTT_BROKER "{{mqttBroker}}"
#define MQTT_TOPIC "{{mqttTopic}}"
{{/if}}

#endif // CONFIG_H
