// {{projectName}} — Microcontroller Firmware
// {{summary}}
// Generated by TheShipboard

{{configInclude}}
{{includes}}

{{pinDefinitions}}

{{sensorDeclarations}}
{{actuatorDeclarations}}

{{#if hasWifi}}
#include <WiFi.h>
const char* ssid = "{{wifiSsid}}";
const char* password = "YOUR_PASSWORD";
{{/if}}

{{#if hasMqtt}}
#include <PubSubClient.h>
WiFiClient espClient;
PubSubClient mqtt(espClient);
{{/if}}

void setup() {
  Serial.begin(115200);
  Serial.println("{{projectName}} starting...");

{{sensorInitialization}}
{{actuatorInitialization}}

{{#if hasWifi}}
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\nWiFi connected: " + WiFi.localIP().toString());
{{/if}}

{{#if hasMqtt}}
  mqtt.setServer("{{mqttBroker}}", 1883);
{{/if}}

  Serial.println("Setup complete.");
}

void loop() {
{{#if hasMqtt}}
  if (!mqtt.connected()) {
    mqtt.connect("{{projectName}}");
  }
  mqtt.loop();
{{/if}}

{{sensorReads}}

{{logicRules}}

  delay({{loopDelay}});
}
