; PlatformIO Configuration — {{projectName}}
; Generated by TheShipboard

[env:{{boardId}}]
platform = auto
board = {{boardId}}
framework = {{framework}}
monitor_speed = 115200

lib_deps =
{{libDeps}}
