// {{projectName}} — Robotics Firmware
// {{summary}}
// Generated by TheShipboard

{{configInclude}}
{{includes}}

{{pinDefinitions}}
{{sensorDeclarations}}
{{actuatorDeclarations}}

void setup() {
  Serial.begin(115200);
  Serial.println("{{projectName}} — Robotics init...");

{{sensorInitialization}}
{{actuatorInitialization}}

  Serial.println("Robotics setup complete.");
}

void loop() {
{{sensorReads}}
{{logicRules}}
  delay({{loopDelay}});
}
