# {{projectName}} — FPGA Build
# Generated by TheShipboard

PROJECT = {{projectName}}
TOP = top

# Yosys + nextpnr flow
synth:
	yosys -p "read_verilog rtl/$(TOP).v; synth_ice40 -top $(TOP) -json $(PROJECT).json"

pnr:
	nextpnr-ice40 --hx8k --json $(PROJECT).json --asc $(PROJECT).asc

pack:
	icepack $(PROJECT).asc $(PROJECT).bin

prog:
	iceprog $(PROJECT).bin

all: synth pnr pack

clean:
	rm -f *.json *.asc *.bin

.PHONY: synth pnr pack prog all clean
