// {{projectName}} — FPGA Top Module
// {{summary}}
// Generated by TheShipboard

module top (
    input wire clk,
    input wire rst_n,
{{ports}}
);

// Clock and reset
reg [31:0] counter;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        counter <= 32'd0;
    end else begin
        counter <= counter + 1;
{{logicRules}}
    end
end

endmodule
