// {{projectName}} — Drone/UAV Firmware
// {{summary}}
// Generated by TheShipboard

{{configInclude}}
{{includes}}

{{pinDefinitions}}
{{sensorDeclarations}}
{{actuatorDeclarations}}

void setup() {
  Serial.begin(115200);
  Serial.println("{{projectName}} — Flight controller init...");

{{sensorInitialization}}
{{actuatorInitialization}}

  Serial.println("Drone setup complete. DISARMED.");
}

void loop() {
{{sensorReads}}
{{logicRules}}
  delay({{loopDelay}});
}
