#!/usr/bin/env python3
"""{{projectName}} — Linux SBC Application
{{summary}}
Generated by TheShipboard
"""

{{imports}}

{{gpioSetup}}

def main():
    print("{{projectName}} starting...")
    try:
        while True:
{{sensorReads}}
{{logicRules}}
            time.sleep({{loopDelay}})
    except KeyboardInterrupt:
        print("Shutting down...")
    finally:
        GPIO.cleanup()

if __name__ == "__main__":
    main()
