-- Seed starter project templates
INSERT INTO project_templates (name, description, category, board_id, difficulty_level, subject_area, behavior_spec, learning_objectives, estimated_minutes, is_public) VALUES
('LED Blink', 'Basic LED blinking tutorial — the Hello World of embedded systems', 'MICROCONTROLLER', 'arduino-uno-r3', 'BEGINNER', 'Digital Output', 'Blink an LED on pin 13 at 1 second intervals', '["Understand digital output", "Learn setup() and loop() structure", "Use delay() function"]', 15, true),
('Temperature Monitor', 'Read temperature from DHT22 and display on serial monitor', 'MICROCONTROLLER', 'esp32-devkit-v1', 'BEGINNER', 'Sensors', 'Read DHT22 sensor every 2 seconds and print temperature and humidity to serial', '["Read sensor data via digital pin", "Parse sensor output", "Serial communication basics"]', 30, true),
('WiFi Weather Station', 'ESP32 weather station with BME280 sensor and web dashboard', 'MICROCONTROLLER', 'esp32-devkit-v1', 'INTERMEDIATE', 'IoT', 'Read BME280 temperature, humidity, and pressure. Serve a web page showing live data. Update every 5 seconds.', '["I2C communication", "WiFi setup and web server", "HTML templating", "Sensor data formatting"]', 60, true),
('MQTT Smart Relay', 'Control a relay via MQTT commands from any device', 'MICROCONTROLLER', 'esp32-devkit-v1', 'INTERMEDIATE', 'IoT', 'Connect to WiFi and MQTT broker. Subscribe to topic home/relay. Turn relay on/off based on MQTT messages. Publish relay status.', '["MQTT protocol", "WiFi connectivity", "Relay control", "Pub/sub messaging"]', 45, true),
('Line Following Robot', 'Arduino robot that follows a black line using IR sensors', 'ROBOTICS', 'arduino-uno-r3', 'INTERMEDIATE', 'Robotics', 'Use 3 IR line sensors. Two DC motors via L298N. Follow black line on white surface. PID control optional.', '["Motor control with H-bridge", "IR sensor reading", "Basic control algorithms", "PWM speed control"]', 90, true),
('MicroPython Sensor Hub', 'Pico W collecting sensor data and sending to cloud', 'MICROPYTHON', 'rpi-pico-w', 'BEGINNER', 'IoT', 'Read temperature from onboard sensor. Connect to WiFi. Send data via HTTP POST every 30 seconds.', '["MicroPython basics", "WiFi with urequests", "JSON formatting", "Periodic tasks"]', 45, true),
('CNC Pen Plotter', 'Simple 2-axis pen plotter using stepper motors', 'CNC', 'arduino-uno-r3', 'ADVANCED', 'CNC', 'Control 2 stepper motors via A4988 drivers. Accept G-code via serial. Implement G0, G1, G28 commands. Servo for pen up/down.', '["Stepper motor control", "G-code parsing", "Coordinate systems", "Serial protocol"]', 120, true),
('BLE Heart Rate Wearable', 'Wearable heart rate monitor with BLE broadcasting', 'WEARABLE', 'esp32-c3-wearable', 'INTERMEDIATE', 'Wearable', 'Read MAX30102 pulse sensor. Calculate BPM. Broadcast via BLE Heart Rate service. Display on OLED.', '["BLE services and characteristics", "Pulse sensor signal processing", "OLED display", "Low power design"]', 90, true)
ON CONFLICT DO NOTHING;
