// {{projectName}} — Wearable/IoT Firmware
// {{summary}}
// Generated by TheShipboard

{{configInclude}}
{{includes}}

{{pinDefinitions}}
{{sensorDeclarations}}
{{actuatorDeclarations}}

{{#if hasBle}}
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>
{{/if}}

void setup() {
  Serial.begin(115200);
  Serial.println("{{projectName}} — Wearable init...");
{{sensorInitialization}}
{{actuatorInitialization}}

{{#if hasBle}}
  BLEDevice::init("{{projectName}}");
{{/if}}

  Serial.println("Wearable ready.");
}

void loop() {
{{sensorReads}}
{{logicRules}}
  delay({{loopDelay}});
}
