// {{projectName}} — CNC/3D Printer Firmware
// {{summary}}
// Generated by TheShipboard

{{configInclude}}
{{includes}}

{{pinDefinitions}}
{{sensorDeclarations}}
{{actuatorDeclarations}}

void setup() {
  Serial.begin(115200);
  Serial.println("{{projectName}} — CNC init...");
{{sensorInitialization}}
{{actuatorInitialization}}
  Serial.println("CNC ready.");
}

void loop() {
{{sensorReads}}
{{logicRules}}
  delay({{loopDelay}});
}
