import type { HardwareComponent, BoardPinMap, BoardGpioPin } from './designerTypes';

// ---------- Component Catalog (mirrors LibraryCatalog.java) ----------

export const COMPONENT_CATALOG: HardwareComponent[] = [
  // ── Sensors ──
  { id: 'dht11', name: 'DHT11', category: 'sensor', description: 'Temperature & humidity', icon: 'Thermometer',
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'dht22', name: 'DHT22', category: 'sensor', description: 'Temperature & humidity (precision)', icon: 'Thermometer',
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'bme280', name: 'BME280', category: 'sensor', description: 'Temp/humidity/pressure', icon: 'CloudRain',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'bmp280', name: 'BMP280', category: 'sensor', description: 'Temperature/pressure', icon: 'Gauge',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'mpu6050', name: 'MPU6050', category: 'sensor', description: '6-axis IMU', icon: 'Move3d',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'int', label: 'INT', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'hcsr04', name: 'HC-SR04', category: 'sensor', description: 'Ultrasonic distance', icon: 'Radar',
    pins: [
      { id: 'trig', label: 'TRIG', type: 'digital', side: 'right', required: true },
      { id: 'echo', label: 'ECHO', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'ds18b20', name: 'DS18B20', category: 'sensor', description: '1-Wire temperature', icon: 'Thermometer',
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'bh1750', name: 'BH1750', category: 'sensor', description: 'Light intensity', icon: 'Sun',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'max30102', name: 'MAX30102', category: 'sensor', description: 'Pulse oximeter', icon: 'HeartPulse',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'int', label: 'INT', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'ina219', name: 'INA219', category: 'sensor', description: 'Current/voltage monitor', icon: 'Zap',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'vl53l0x', name: 'VL53L0X', category: 'sensor', description: 'ToF distance sensor', icon: 'Crosshair',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'xshut', label: 'XSHUT', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'ads1115', name: 'ADS1115', category: 'sensor', description: '16-bit ADC', icon: 'Activity',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },

  // ── Displays ──
  { id: 'ssd1306', name: 'SSD1306', category: 'display', description: '128x64 OLED', icon: 'Monitor',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'lcd1602', name: 'LCD1602', category: 'display', description: '16x2 LCD I2C', icon: 'SquareTerminal',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'st7735', name: 'ST7735', category: 'display', description: 'TFT color display', icon: 'Tv',
    pins: [
      { id: 'cs', label: 'CS', type: 'spi', side: 'right', required: true },
      { id: 'dc', label: 'DC', type: 'digital', side: 'right', required: true },
      { id: 'mosi', label: 'MOSI', type: 'spi', side: 'right', required: true },
      { id: 'sclk', label: 'SCLK', type: 'spi', side: 'right', required: true },
      { id: 'rst', label: 'RST', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'ili9341', name: 'ILI9341', category: 'display', description: '2.4" TFT display', icon: 'Tv',
    pins: [
      { id: 'cs', label: 'CS', type: 'spi', side: 'right', required: true },
      { id: 'dc', label: 'DC', type: 'digital', side: 'right', required: true },
      { id: 'mosi', label: 'MOSI', type: 'spi', side: 'right', required: true },
      { id: 'sclk', label: 'SCLK', type: 'spi', side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi', side: 'right', required: false },
      { id: 'rst', label: 'RST', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'neopixel', name: 'NeoPixel', category: 'display', description: 'WS2812B LED strip', icon: 'Lightbulb',
    pins: [
      { id: 'din', label: 'DIN', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'max7219', name: 'MAX7219', category: 'display', description: 'LED matrix driver', icon: 'LayoutGrid',
    pins: [
      { id: 'din', label: 'DIN', type: 'spi', side: 'right', required: true },
      { id: 'cs', label: 'CS', type: 'spi', side: 'right', required: true },
      { id: 'clk', label: 'CLK', type: 'spi', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },

  // ── Actuators ──
  { id: 'servo', name: 'Servo', category: 'actuator', description: 'Standard servo motor', icon: 'RotateCw',
    pins: [
      { id: 'signal', label: 'SIG', type: 'pwm', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'pca9685', name: 'PCA9685', category: 'actuator', description: '16-ch PWM driver', icon: 'Sliders',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'stepper_a4988', name: 'A4988 Stepper', category: 'actuator', description: 'Stepper motor driver', icon: 'Disc',
    pins: [
      { id: 'step', label: 'STEP', type: 'digital', side: 'right', required: true },
      { id: 'dir', label: 'DIR', type: 'digital', side: 'right', required: true },
      { id: 'en', label: 'EN', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'tmc2209', name: 'TMC2209', category: 'actuator', description: 'TMC2209 stepper driver', icon: 'Disc',
    pins: [
      { id: 'step', label: 'STEP', type: 'digital', side: 'right', required: true },
      { id: 'dir', label: 'DIR', type: 'digital', side: 'right', required: true },
      { id: 'en', label: 'EN', type: 'digital', side: 'right', required: false },
      { id: 'rx', label: 'RX', type: 'uart', side: 'right', required: false },
      { id: 'tx', label: 'TX', type: 'uart', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'l298n', name: 'L298N', category: 'actuator', description: 'Dual H-bridge motor driver', icon: 'Cog',
    pins: [
      { id: 'in1', label: 'IN1', type: 'digital', side: 'right', required: true },
      { id: 'in2', label: 'IN2', type: 'digital', side: 'right', required: true },
      { id: 'ena', label: 'ENA', type: 'pwm', side: 'right', required: true },
      { id: 'in3', label: 'IN3', type: 'digital', side: 'right', required: false },
      { id: 'in4', label: 'IN4', type: 'digital', side: 'right', required: false },
      { id: 'enb', label: 'ENB', type: 'pwm', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'relay', name: 'Relay', category: 'actuator', description: 'Relay module', icon: 'ToggleRight',
    pins: [
      { id: 'signal', label: 'SIG', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },

  // ── Communication ──
  { id: 'wifi', name: 'WiFi', category: 'communication', description: 'ESP32 WiFi (built-in)', icon: 'Wifi',
    pins: [] },
  { id: 'ble', name: 'BLE', category: 'communication', description: 'ESP32 BLE (built-in)', icon: 'Bluetooth',
    pins: [] },
  { id: 'mqtt', name: 'MQTT', category: 'communication', description: 'MQTT client (over WiFi)', icon: 'MessageSquare',
    pins: [] },
  { id: 'lorawan', name: 'LoRaWAN', category: 'communication', description: 'LoRaWAN radio', icon: 'Radio',
    pins: [
      { id: 'cs', label: 'CS', type: 'spi', side: 'right', required: true },
      { id: 'mosi', label: 'MOSI', type: 'spi', side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi', side: 'right', required: true },
      { id: 'sclk', label: 'SCLK', type: 'spi', side: 'right', required: true },
      { id: 'rst', label: 'RST', type: 'digital', side: 'right', required: true },
      { id: 'dio0', label: 'DIO0', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'espnow', name: 'ESP-NOW', category: 'communication', description: 'ESP-NOW protocol (built-in)', icon: 'Radio',
    pins: [] },
  { id: 'can_bus', name: 'CAN Bus', category: 'communication', description: 'CAN bus MCP2515', icon: 'Cable',
    pins: [
      { id: 'cs', label: 'CS', type: 'spi', side: 'right', required: true },
      { id: 'mosi', label: 'MOSI', type: 'spi', side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi', side: 'right', required: true },
      { id: 'sclk', label: 'SCLK', type: 'spi', side: 'right', required: true },
      { id: 'int', label: 'INT', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'modbus_rtu', name: 'Modbus RTU', category: 'communication', description: 'Modbus RTU', icon: 'Network',
    pins: [
      { id: 'rx', label: 'RX', type: 'uart', side: 'right', required: true },
      { id: 'tx', label: 'TX', type: 'uart', side: 'right', required: true },
      { id: 'de', label: 'DE', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'rs485', name: 'RS-485', category: 'communication', description: 'RS-485 transceiver', icon: 'Network',
    pins: [
      { id: 'rx', label: 'RX', type: 'uart', side: 'right', required: true },
      { id: 'tx', label: 'TX', type: 'uart', side: 'right', required: true },
      { id: 'de', label: 'DE', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },

  // ── Storage ──
  { id: 'sd_card', name: 'SD Card', category: 'storage', description: 'SD card module', icon: 'HardDrive',
    pins: [
      { id: 'cs', label: 'CS', type: 'spi', side: 'right', required: true },
      { id: 'mosi', label: 'MOSI', type: 'spi', side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi', side: 'right', required: true },
      { id: 'sclk', label: 'SCLK', type: 'spi', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'eeprom', name: 'EEPROM', category: 'storage', description: 'EEPROM storage (built-in)', icon: 'Database',
    pins: [] },
  { id: 'spiffs', name: 'SPIFFS', category: 'storage', description: 'SPI Flash FS (built-in)', icon: 'Database',
    pins: [] },
  { id: 'littlefs', name: 'LittleFS', category: 'storage', description: 'LittleFS (built-in)', icon: 'Database',
    pins: [] },

  // ── Audio ──
  { id: 'i2s_dac', name: 'I2S DAC', category: 'audio', description: 'I2S DAC audio output', icon: 'Volume2',
    pins: [
      { id: 'bclk', label: 'BCLK', type: 'digital', side: 'right', required: true },
      { id: 'lrc', label: 'LRC', type: 'digital', side: 'right', required: true },
      { id: 'dout', label: 'DOUT', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'dfplayer', name: 'DFPlayer', category: 'audio', description: 'DFPlayer Mini MP3', icon: 'Music',
    pins: [
      { id: 'rx', label: 'RX', type: 'uart', side: 'right', required: true },
      { id: 'tx', label: 'TX', type: 'uart', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },

  // ── Motor Control ──
  { id: 'simplefoc', name: 'SimpleFOC', category: 'motor', description: 'Field Oriented Control', icon: 'Cog',
    pins: [
      { id: 'pwm_a', label: 'PWM_A', type: 'pwm', side: 'right', required: true },
      { id: 'pwm_b', label: 'PWM_B', type: 'pwm', side: 'right', required: true },
      { id: 'pwm_c', label: 'PWM_C', type: 'pwm', side: 'right', required: true },
      { id: 'en', label: 'EN', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'encoder', name: 'Encoder', category: 'motor', description: 'Rotary encoder', icon: 'CircleDot',
    pins: [
      { id: 'clk', label: 'CLK', type: 'digital', side: 'right', required: true },
      { id: 'dt', label: 'DT', type: 'digital', side: 'right', required: true },
      { id: 'sw', label: 'SW', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },

  // ── RTC / Timing ──
  { id: 'ds3231', name: 'DS3231', category: 'timing', description: 'Real-time clock', icon: 'Clock',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c', side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'ntp', name: 'NTP', category: 'timing', description: 'NTP time sync (over WiFi)', icon: 'Clock',
    pins: [] },

  // ── Misc ──
  { id: 'rfid_rc522', name: 'RFID RC522', category: 'misc', description: 'RFID reader', icon: 'CreditCard',
    pins: [
      { id: 'cs', label: 'SDA', type: 'spi', side: 'right', required: true },
      { id: 'sck', label: 'SCK', type: 'spi', side: 'right', required: true },
      { id: 'mosi', label: 'MOSI', type: 'spi', side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi', side: 'right', required: true },
      { id: 'rst', label: 'RST', type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'keypad', name: 'Keypad', category: 'misc', description: 'Matrix keypad', icon: 'Grid3x3',
    pins: [
      { id: 'r1', label: 'R1', type: 'digital', side: 'right', required: true },
      { id: 'r2', label: 'R2', type: 'digital', side: 'right', required: true },
      { id: 'r3', label: 'R3', type: 'digital', side: 'right', required: true },
      { id: 'r4', label: 'R4', type: 'digital', side: 'right', required: true },
      { id: 'c1', label: 'C1', type: 'digital', side: 'right', required: true },
      { id: 'c2', label: 'C2', type: 'digital', side: 'right', required: true },
      { id: 'c3', label: 'C3', type: 'digital', side: 'right', required: true },
    ] },
  { id: 'ir_remote', name: 'IR Remote', category: 'misc', description: 'IR receiver/transmitter', icon: 'Flashlight',
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
  { id: 'gps_neo6m', name: 'GPS NEO-6M', category: 'misc', description: 'GPS module', icon: 'MapPin',
    pins: [
      { id: 'rx', label: 'RX', type: 'uart', side: 'right', required: true },
      { id: 'tx', label: 'TX', type: 'uart', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ] },
];

// ---------- Board Pin Maps ----------

function gpio(id: string, label: string, caps: string[], side: 'left' | 'right', alt?: string): BoardGpioPin {
  return { id, label, altFunction: alt, capabilities: caps, side };
}

const DIGITAL = ['digital'];
const DIGITAL_PWM = ['digital', 'pwm'];
const DIGITAL_ADC = ['digital', 'analog'];
const I2C_CAPS = ['digital', 'i2c'];
const SPI_CAPS = ['digital', 'spi'];
const UART_CAPS = ['digital', 'uart'];
const ALL = ['digital', 'pwm', 'analog'];
const POWER: string[] = ['power'];
const GROUND: string[] = ['ground'];

export const BOARD_PIN_MAPS: BoardPinMap[] = [
  { id: 'esp32_devkit_v1', pins: [
    // Left side
    gpio('3v3', '3V3', POWER, 'left'),
    gpio('gnd1', 'GND', GROUND, 'left'),
    gpio('gpio15', 'GPIO15', DIGITAL_PWM, 'left'),
    gpio('gpio2', 'GPIO2', DIGITAL_PWM, 'left'),
    gpio('gpio4', 'GPIO4', DIGITAL_PWM, 'left'),
    gpio('gpio16', 'GPIO16', DIGITAL_PWM, 'left', 'RX2'),
    gpio('gpio17', 'GPIO17', DIGITAL_PWM, 'left', 'TX2'),
    gpio('gpio5', 'GPIO5', DIGITAL_PWM, 'left', 'SS'),
    gpio('gpio18', 'GPIO18', SPI_CAPS, 'left', 'SCK'),
    gpio('gpio19', 'GPIO19', SPI_CAPS, 'left', 'MISO'),
    gpio('gpio21', 'GPIO21', I2C_CAPS, 'left', 'SDA'),
    gpio('gpio3', 'GPIO3', UART_CAPS, 'left', 'RX0'),
    gpio('gpio1', 'GPIO1', UART_CAPS, 'left', 'TX0'),
    gpio('gpio22', 'GPIO22', I2C_CAPS, 'left', 'SCL'),
    gpio('gpio23', 'GPIO23', SPI_CAPS, 'left', 'MOSI'),
    // Right side
    gpio('vin', 'VIN', POWER, 'right'),
    gpio('gnd2', 'GND', GROUND, 'right'),
    gpio('gpio13', 'GPIO13', ALL, 'right'),
    gpio('gpio12', 'GPIO12', ALL, 'right'),
    gpio('gpio14', 'GPIO14', ALL, 'right'),
    gpio('gpio27', 'GPIO27', ALL, 'right'),
    gpio('gpio26', 'GPIO26', ALL, 'right'),
    gpio('gpio25', 'GPIO25', ALL, 'right'),
    gpio('gpio33', 'GPIO33', DIGITAL_ADC, 'right'),
    gpio('gpio32', 'GPIO32', DIGITAL_ADC, 'right'),
    gpio('gpio35', 'GPIO35', ['analog'], 'right'),
    gpio('gpio34', 'GPIO34', ['analog'], 'right'),
    gpio('svn', 'SVN', ['analog'], 'right'),
    gpio('svp', 'SVP', ['analog'], 'right'),
    gpio('en', 'EN', DIGITAL, 'right'),
  ] },
  { id: 'arduino_uno', pins: [
    // Left (digital)
    gpio('d0', 'D0', UART_CAPS, 'left', 'RX'),
    gpio('d1', 'D1', UART_CAPS, 'left', 'TX'),
    gpio('d2', 'D2', DIGITAL, 'left'),
    gpio('d3', 'D3', DIGITAL_PWM, 'left'),
    gpio('d4', 'D4', DIGITAL, 'left'),
    gpio('d5', 'D5', DIGITAL_PWM, 'left'),
    gpio('d6', 'D6', DIGITAL_PWM, 'left'),
    gpio('d7', 'D7', DIGITAL, 'left'),
    gpio('d8', 'D8', DIGITAL, 'left'),
    gpio('d9', 'D9', DIGITAL_PWM, 'left'),
    gpio('d10', 'D10', SPI_CAPS, 'left', 'SS'),
    gpio('d11', 'D11', SPI_CAPS, 'left', 'MOSI'),
    gpio('d12', 'D12', SPI_CAPS, 'left', 'MISO'),
    gpio('d13', 'D13', SPI_CAPS, 'left', 'SCK'),
    // Right (analog + power)
    gpio('a0', 'A0', DIGITAL_ADC, 'right'),
    gpio('a1', 'A1', DIGITAL_ADC, 'right'),
    gpio('a2', 'A2', DIGITAL_ADC, 'right'),
    gpio('a3', 'A3', DIGITAL_ADC, 'right'),
    gpio('a4', 'A4', [...DIGITAL_ADC, 'i2c'], 'right', 'SDA'),
    gpio('a5', 'A5', [...DIGITAL_ADC, 'i2c'], 'right', 'SCL'),
    gpio('5v', '5V', POWER, 'right'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd1', 'GND', GROUND, 'right'),
    gpio('gnd2', 'GND', GROUND, 'right'),
    gpio('vin', 'VIN', POWER, 'right'),
  ] },
  { id: 'arduino_nano', pins: [
    gpio('d2', 'D2', DIGITAL, 'left'),
    gpio('d3', 'D3', DIGITAL_PWM, 'left'),
    gpio('d4', 'D4', DIGITAL, 'left'),
    gpio('d5', 'D5', DIGITAL_PWM, 'left'),
    gpio('d6', 'D6', DIGITAL_PWM, 'left'),
    gpio('d7', 'D7', DIGITAL, 'left'),
    gpio('d8', 'D8', DIGITAL, 'left'),
    gpio('d9', 'D9', DIGITAL_PWM, 'left'),
    gpio('d10', 'D10', SPI_CAPS, 'left', 'SS'),
    gpio('d11', 'D11', SPI_CAPS, 'left', 'MOSI'),
    gpio('d12', 'D12', SPI_CAPS, 'left', 'MISO'),
    gpio('d13', 'D13', SPI_CAPS, 'left', 'SCK'),
    gpio('a0', 'A0', DIGITAL_ADC, 'right'),
    gpio('a1', 'A1', DIGITAL_ADC, 'right'),
    gpio('a2', 'A2', DIGITAL_ADC, 'right'),
    gpio('a3', 'A3', DIGITAL_ADC, 'right'),
    gpio('a4', 'A4', [...DIGITAL_ADC, 'i2c'], 'right', 'SDA'),
    gpio('a5', 'A5', [...DIGITAL_ADC, 'i2c'], 'right', 'SCL'),
    gpio('a6', 'A6', ['analog'], 'right'),
    gpio('a7', 'A7', ['analog'], 'right'),
    gpio('5v', '5V', POWER, 'right'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd', 'GND', GROUND, 'right'),
    gpio('vin', 'VIN', POWER, 'right'),
  ] },
  { id: 'esp32_s3_devkitc', pins: [
    gpio('3v3', '3V3', POWER, 'left'),
    gpio('gnd1', 'GND', GROUND, 'left'),
    gpio('gpio1', 'GPIO1', ALL, 'left'),
    gpio('gpio2', 'GPIO2', ALL, 'left'),
    gpio('gpio3', 'GPIO3', ALL, 'left'),
    gpio('gpio4', 'GPIO4', ALL, 'left'),
    gpio('gpio5', 'GPIO5', ALL, 'left'),
    gpio('gpio6', 'GPIO6', ALL, 'left'),
    gpio('gpio7', 'GPIO7', ALL, 'left'),
    gpio('gpio8', 'GPIO8', I2C_CAPS, 'left', 'SDA'),
    gpio('gpio9', 'GPIO9', I2C_CAPS, 'left', 'SCL'),
    gpio('gpio10', 'GPIO10', SPI_CAPS, 'left', 'SS'),
    gpio('gpio11', 'GPIO11', SPI_CAPS, 'left', 'MOSI'),
    gpio('gpio12', 'GPIO12', SPI_CAPS, 'left', 'SCK'),
    gpio('gpio13', 'GPIO13', SPI_CAPS, 'left', 'MISO'),
    gpio('gpio14', 'GPIO14', ALL, 'right'),
    gpio('gpio15', 'GPIO15', ALL, 'right'),
    gpio('gpio16', 'GPIO16', ALL, 'right'),
    gpio('gpio17', 'GPIO17', UART_CAPS, 'right', 'TX1'),
    gpio('gpio18', 'GPIO18', UART_CAPS, 'right', 'RX1'),
    gpio('gpio21', 'GPIO21', DIGITAL_PWM, 'right'),
    gpio('gpio35', 'GPIO35', ALL, 'right'),
    gpio('gpio36', 'GPIO36', ALL, 'right'),
    gpio('gpio37', 'GPIO37', ALL, 'right'),
    gpio('gpio38', 'GPIO38', ALL, 'right'),
    gpio('gpio39', 'GPIO39', ALL, 'right'),
    gpio('gpio40', 'GPIO40', ALL, 'right'),
    gpio('gpio41', 'GPIO41', ALL, 'right'),
    gpio('gpio42', 'GPIO42', ALL, 'right'),
    gpio('5v', '5V', POWER, 'right'),
    gpio('gnd2', 'GND', GROUND, 'right'),
  ] },
  { id: 'esp8266_nodemcu', pins: [
    gpio('d0', 'D0/GPIO16', DIGITAL, 'left'),
    gpio('d1', 'D1/GPIO5', [...DIGITAL, 'i2c'], 'left', 'SCL'),
    gpio('d2', 'D2/GPIO4', [...DIGITAL, 'i2c'], 'left', 'SDA'),
    gpio('d3', 'D3/GPIO0', DIGITAL, 'left'),
    gpio('d4', 'D4/GPIO2', DIGITAL, 'left'),
    gpio('d5', 'D5/GPIO14', SPI_CAPS, 'left', 'SCK'),
    gpio('d6', 'D6/GPIO12', SPI_CAPS, 'left', 'MISO'),
    gpio('d7', 'D7/GPIO13', SPI_CAPS, 'left', 'MOSI'),
    gpio('d8', 'D8/GPIO15', SPI_CAPS, 'left', 'SS'),
    gpio('a0', 'A0', ['analog'], 'right'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd', 'GND', GROUND, 'right'),
    gpio('vin', 'VIN', POWER, 'right'),
  ] },
  { id: 'rpi_pico', pins: [
    gpio('gp0', 'GP0', UART_CAPS, 'left', 'TX0'),
    gpio('gp1', 'GP1', UART_CAPS, 'left', 'RX0'),
    gpio('gp2', 'GP2', DIGITAL_PWM, 'left'),
    gpio('gp3', 'GP3', DIGITAL_PWM, 'left'),
    gpio('gp4', 'GP4', [...DIGITAL_PWM, 'i2c'], 'left', 'SDA0'),
    gpio('gp5', 'GP5', [...DIGITAL_PWM, 'i2c'], 'left', 'SCL0'),
    gpio('gp6', 'GP6', DIGITAL_PWM, 'left'),
    gpio('gp7', 'GP7', DIGITAL_PWM, 'left'),
    gpio('gp8', 'GP8', DIGITAL_PWM, 'left'),
    gpio('gp9', 'GP9', DIGITAL_PWM, 'left'),
    gpio('gp10', 'GP10', SPI_CAPS, 'left', 'SCK1'),
    gpio('gp11', 'GP11', SPI_CAPS, 'left', 'TX1'),
    gpio('gp12', 'GP12', SPI_CAPS, 'left', 'RX1'),
    gpio('gp13', 'GP13', SPI_CAPS, 'left', 'CS1'),
    gpio('gp14', 'GP14', DIGITAL_PWM, 'right'),
    gpio('gp15', 'GP15', DIGITAL_PWM, 'right'),
    gpio('gp16', 'GP16', SPI_CAPS, 'right', 'MISO0'),
    gpio('gp17', 'GP17', SPI_CAPS, 'right', 'CS0'),
    gpio('gp18', 'GP18', SPI_CAPS, 'right', 'SCK0'),
    gpio('gp19', 'GP19', SPI_CAPS, 'right', 'MOSI0'),
    gpio('gp20', 'GP20', DIGITAL_PWM, 'right'),
    gpio('gp21', 'GP21', DIGITAL_PWM, 'right'),
    gpio('gp22', 'GP22', DIGITAL_PWM, 'right'),
    gpio('gp26', 'GP26', [...ALL, 'analog'], 'right', 'ADC0'),
    gpio('gp27', 'GP27', [...ALL, 'analog'], 'right', 'ADC1'),
    gpio('gp28', 'GP28', [...ALL, 'analog'], 'right', 'ADC2'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd', 'GND', GROUND, 'right'),
    gpio('vsys', 'VSYS', POWER, 'right'),
  ] },
  { id: 'stm32_bluepill', pins: [
    gpio('pa0', 'PA0', ALL, 'left'),
    gpio('pa1', 'PA1', ALL, 'left'),
    gpio('pa2', 'PA2', [...ALL, 'uart'], 'left', 'TX2'),
    gpio('pa3', 'PA3', [...ALL, 'uart'], 'left', 'RX2'),
    gpio('pa4', 'PA4', [...DIGITAL_ADC, 'spi'], 'left', 'SS1'),
    gpio('pa5', 'PA5', [...DIGITAL_ADC, 'spi'], 'left', 'SCK1'),
    gpio('pa6', 'PA6', [...DIGITAL_ADC, 'spi'], 'left', 'MISO1'),
    gpio('pa7', 'PA7', [...DIGITAL_ADC, 'spi'], 'left', 'MOSI1'),
    gpio('pa8', 'PA8', DIGITAL_PWM, 'left'),
    gpio('pa9', 'PA9', UART_CAPS, 'left', 'TX1'),
    gpio('pa10', 'PA10', UART_CAPS, 'left', 'RX1'),
    gpio('pb0', 'PB0', ALL, 'right'),
    gpio('pb1', 'PB1', ALL, 'right'),
    gpio('pb6', 'PB6', [...DIGITAL, 'i2c'], 'right', 'SCL1'),
    gpio('pb7', 'PB7', [...DIGITAL, 'i2c'], 'right', 'SDA1'),
    gpio('pb8', 'PB8', DIGITAL_PWM, 'right'),
    gpio('pb9', 'PB9', DIGITAL_PWM, 'right'),
    gpio('pb10', 'PB10', UART_CAPS, 'right', 'TX3'),
    gpio('pb11', 'PB11', UART_CAPS, 'right', 'RX3'),
    gpio('pb12', 'PB12', SPI_CAPS, 'right', 'SS2'),
    gpio('pb13', 'PB13', SPI_CAPS, 'right', 'SCK2'),
    gpio('pb14', 'PB14', SPI_CAPS, 'right', 'MISO2'),
    gpio('pb15', 'PB15', SPI_CAPS, 'right', 'MOSI2'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd', 'GND', GROUND, 'right'),
    gpio('5v', '5V', POWER, 'right'),
  ] },
  { id: 'arduino_mega', pins: [
    gpio('d2', 'D2', DIGITAL, 'left'),
    gpio('d3', 'D3', DIGITAL_PWM, 'left'),
    gpio('d4', 'D4', DIGITAL, 'left'),
    gpio('d5', 'D5', DIGITAL_PWM, 'left'),
    gpio('d6', 'D6', DIGITAL_PWM, 'left'),
    gpio('d7', 'D7', DIGITAL, 'left'),
    gpio('d8', 'D8', DIGITAL, 'left'),
    gpio('d9', 'D9', DIGITAL_PWM, 'left'),
    gpio('d10', 'D10', DIGITAL_PWM, 'left'),
    gpio('d11', 'D11', DIGITAL_PWM, 'left'),
    gpio('d12', 'D12', DIGITAL, 'left'),
    gpio('d13', 'D13', DIGITAL_PWM, 'left'),
    gpio('d14', 'D14', UART_CAPS, 'left', 'TX3'),
    gpio('d15', 'D15', UART_CAPS, 'left', 'RX3'),
    gpio('d16', 'D16', UART_CAPS, 'left', 'TX2'),
    gpio('d17', 'D17', UART_CAPS, 'left', 'RX2'),
    gpio('d18', 'D18', UART_CAPS, 'left', 'TX1'),
    gpio('d19', 'D19', UART_CAPS, 'left', 'RX1'),
    gpio('d20', 'D20', I2C_CAPS, 'left', 'SDA'),
    gpio('d21', 'D21', I2C_CAPS, 'left', 'SCL'),
    gpio('d50', 'D50', SPI_CAPS, 'right', 'MISO'),
    gpio('d51', 'D51', SPI_CAPS, 'right', 'MOSI'),
    gpio('d52', 'D52', SPI_CAPS, 'right', 'SCK'),
    gpio('d53', 'D53', SPI_CAPS, 'right', 'SS'),
    gpio('a0', 'A0', DIGITAL_ADC, 'right'),
    gpio('a1', 'A1', DIGITAL_ADC, 'right'),
    gpio('a2', 'A2', DIGITAL_ADC, 'right'),
    gpio('a3', 'A3', DIGITAL_ADC, 'right'),
    gpio('a4', 'A4', DIGITAL_ADC, 'right'),
    gpio('a5', 'A5', DIGITAL_ADC, 'right'),
    gpio('5v', '5V', POWER, 'right'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd1', 'GND', GROUND, 'right'),
    gpio('gnd2', 'GND', GROUND, 'right'),
    gpio('vin', 'VIN', POWER, 'right'),
  ] },
  { id: 'esp32_c3_mini', pins: [
    gpio('gpio0', 'GPIO0', ALL, 'left'),
    gpio('gpio1', 'GPIO1', ALL, 'left'),
    gpio('gpio2', 'GPIO2', ALL, 'left'),
    gpio('gpio3', 'GPIO3', ALL, 'left'),
    gpio('gpio4', 'GPIO4', [...ALL, 'i2c'], 'left', 'SDA'),
    gpio('gpio5', 'GPIO5', [...ALL, 'i2c'], 'left', 'SCL'),
    gpio('gpio6', 'GPIO6', SPI_CAPS, 'right', 'SCK'),
    gpio('gpio7', 'GPIO7', SPI_CAPS, 'right', 'MOSI'),
    gpio('gpio8', 'GPIO8', DIGITAL, 'right'),
    gpio('gpio9', 'GPIO9', DIGITAL, 'right'),
    gpio('gpio10', 'GPIO10', SPI_CAPS, 'right', 'MISO'),
    gpio('gpio20', 'GPIO20', UART_CAPS, 'right', 'RX'),
    gpio('gpio21', 'GPIO21', UART_CAPS, 'right', 'TX'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd', 'GND', GROUND, 'right'),
    gpio('5v', '5V', POWER, 'right'),
  ] },
  { id: 'teensy_40', pins: [
    gpio('d0', 'D0', UART_CAPS, 'left', 'RX1'),
    gpio('d1', 'D1', UART_CAPS, 'left', 'TX1'),
    gpio('d2', 'D2', DIGITAL_PWM, 'left'),
    gpio('d3', 'D3', DIGITAL_PWM, 'left'),
    gpio('d4', 'D4', DIGITAL_PWM, 'left'),
    gpio('d5', 'D5', DIGITAL_PWM, 'left'),
    gpio('d6', 'D6', DIGITAL_PWM, 'left'),
    gpio('d7', 'D7', UART_CAPS, 'left', 'RX2'),
    gpio('d8', 'D8', UART_CAPS, 'left', 'TX2'),
    gpio('d9', 'D9', DIGITAL_PWM, 'left'),
    gpio('d10', 'D10', SPI_CAPS, 'left', 'CS0'),
    gpio('d11', 'D11', SPI_CAPS, 'left', 'MOSI0'),
    gpio('d12', 'D12', SPI_CAPS, 'left', 'MISO0'),
    gpio('d13', 'D13', SPI_CAPS, 'left', 'SCK0'),
    gpio('d14', 'D14', DIGITAL_ADC, 'right'),
    gpio('d15', 'D15', DIGITAL_ADC, 'right'),
    gpio('d16', 'D16', DIGITAL_ADC, 'right'),
    gpio('d17', 'D17', DIGITAL_ADC, 'right'),
    gpio('d18', 'D18', [...DIGITAL_ADC, 'i2c'], 'right', 'SDA0'),
    gpio('d19', 'D19', [...DIGITAL_ADC, 'i2c'], 'right', 'SCL0'),
    gpio('d20', 'D20', DIGITAL_ADC, 'right'),
    gpio('d21', 'D21', DIGITAL_ADC, 'right'),
    gpio('d22', 'D22', DIGITAL_PWM, 'right'),
    gpio('d23', 'D23', DIGITAL_PWM, 'right'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd', 'GND', GROUND, 'right'),
    gpio('vin', 'VIN', POWER, 'right'),
  ] },
  { id: 'esp32_wroom_32', pins: [
    // Alias for esp32_devkit_v1 — same pinout
    gpio('3v3', '3V3', POWER, 'left'),
    gpio('gnd1', 'GND', GROUND, 'left'),
    gpio('gpio15', 'GPIO15', DIGITAL_PWM, 'left'),
    gpio('gpio2', 'GPIO2', DIGITAL_PWM, 'left'),
    gpio('gpio4', 'GPIO4', DIGITAL_PWM, 'left'),
    gpio('gpio16', 'GPIO16', DIGITAL_PWM, 'left', 'RX2'),
    gpio('gpio17', 'GPIO17', DIGITAL_PWM, 'left', 'TX2'),
    gpio('gpio5', 'GPIO5', DIGITAL_PWM, 'left', 'SS'),
    gpio('gpio18', 'GPIO18', SPI_CAPS, 'left', 'SCK'),
    gpio('gpio19', 'GPIO19', SPI_CAPS, 'left', 'MISO'),
    gpio('gpio21', 'GPIO21', I2C_CAPS, 'left', 'SDA'),
    gpio('gpio3', 'GPIO3', UART_CAPS, 'left', 'RX0'),
    gpio('gpio1', 'GPIO1', UART_CAPS, 'left', 'TX0'),
    gpio('gpio22', 'GPIO22', I2C_CAPS, 'left', 'SCL'),
    gpio('gpio23', 'GPIO23', SPI_CAPS, 'left', 'MOSI'),
    gpio('vin', 'VIN', POWER, 'right'),
    gpio('gnd2', 'GND', GROUND, 'right'),
    gpio('gpio13', 'GPIO13', ALL, 'right'),
    gpio('gpio12', 'GPIO12', ALL, 'right'),
    gpio('gpio14', 'GPIO14', ALL, 'right'),
    gpio('gpio27', 'GPIO27', ALL, 'right'),
    gpio('gpio26', 'GPIO26', ALL, 'right'),
    gpio('gpio25', 'GPIO25', ALL, 'right'),
    gpio('gpio33', 'GPIO33', DIGITAL_ADC, 'right'),
    gpio('gpio32', 'GPIO32', DIGITAL_ADC, 'right'),
    gpio('gpio35', 'GPIO35', ['analog'], 'right'),
    gpio('gpio34', 'GPIO34', ['analog'], 'right'),
    gpio('svn', 'SVN', ['analog'], 'right'),
    gpio('svp', 'SVP', ['analog'], 'right'),
    gpio('en', 'EN', DIGITAL, 'right'),
  ] },
  { id: 'arduino_leonardo', pins: [
    gpio('d0', 'D0', UART_CAPS, 'left', 'RX'),
    gpio('d1', 'D1', UART_CAPS, 'left', 'TX'),
    gpio('d2', 'D2', DIGITAL, 'left', 'SDA'),
    gpio('d3', 'D3', DIGITAL_PWM, 'left', 'SCL'),
    gpio('d4', 'D4', DIGITAL, 'left'),
    gpio('d5', 'D5', DIGITAL_PWM, 'left'),
    gpio('d6', 'D6', DIGITAL_PWM, 'left'),
    gpio('d7', 'D7', DIGITAL, 'left'),
    gpio('d8', 'D8', DIGITAL, 'left'),
    gpio('d9', 'D9', DIGITAL_PWM, 'left'),
    gpio('d10', 'D10', DIGITAL_PWM, 'left'),
    gpio('d11', 'D11', DIGITAL_PWM, 'left'),
    gpio('d12', 'D12', DIGITAL, 'left'),
    gpio('d13', 'D13', DIGITAL_PWM, 'left'),
    gpio('a0', 'A0', DIGITAL_ADC, 'right'),
    gpio('a1', 'A1', DIGITAL_ADC, 'right'),
    gpio('a2', 'A2', DIGITAL_ADC, 'right'),
    gpio('a3', 'A3', DIGITAL_ADC, 'right'),
    gpio('a4', 'A4', DIGITAL_ADC, 'right'),
    gpio('a5', 'A5', DIGITAL_ADC, 'right'),
    gpio('5v', '5V', POWER, 'right'),
    gpio('3v3', '3V3', POWER, 'right'),
    gpio('gnd', 'GND', GROUND, 'right'),
    gpio('vin', 'VIN', POWER, 'right'),
  ] },
];

// Build generic pin list from board interfaces when no pin map is available
export function buildGenericPins(interfaces: string[]): BoardGpioPin[] {
  const pins: BoardGpioPin[] = [];
  const gpioCount = 20;
  for (let i = 0; i < gpioCount; i++) {
    const side = i < gpioCount / 2 ? 'left' as const : 'right' as const;
    const caps = ['digital'];
    if (interfaces.includes('PWM')) caps.push('pwm');
    if (interfaces.includes('I2C') && (i === 4 || i === 5)) caps.push('i2c');
    if (interfaces.includes('SPI') && (i >= 10 && i <= 13)) caps.push('spi');
    if (interfaces.includes('UART') && (i === 0 || i === 1)) caps.push('uart');
    if (interfaces.includes('ADC') && i >= 14) caps.push('analog');
    const alt = caps.includes('i2c') ? (i === 4 ? 'SDA' : 'SCL') : undefined;
    pins.push(gpio(`gpio${i}`, `GPIO${i}`, caps, side, alt));
  }
  pins.push(gpio('3v3', '3V3', POWER, 'right'));
  pins.push(gpio('gnd', 'GND', GROUND, 'right'));
  pins.push(gpio('5v', '5V', POWER, 'right'));
  return pins;
}

// Category display info
export const CATEGORY_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  sensor:        { bg: 'bg-amber-900/30',   border: 'border-amber-700', text: 'text-amber-400' },
  display:       { bg: 'bg-blue-900/30',     border: 'border-blue-700',  text: 'text-blue-400' },
  actuator:      { bg: 'bg-green-900/30',    border: 'border-green-700', text: 'text-green-400' },
  communication: { bg: 'bg-purple-900/30',   border: 'border-purple-700', text: 'text-purple-400' },
  storage:       { bg: 'bg-cyan-900/30',     border: 'border-cyan-700',  text: 'text-cyan-400' },
  audio:         { bg: 'bg-pink-900/30',     border: 'border-pink-700',  text: 'text-pink-400' },
  motor:         { bg: 'bg-red-900/30',      border: 'border-red-700',   text: 'text-red-400' },
  timing:        { bg: 'bg-indigo-900/30',   border: 'border-indigo-700', text: 'text-indigo-400' },
  misc:          { bg: 'bg-gray-800/30',     border: 'border-gray-600',  text: 'text-gray-400' },
};

export const CATEGORY_LABELS: Record<string, string> = {
  sensor: 'Sensors',
  display: 'Displays',
  actuator: 'Actuators',
  communication: 'Communication',
  storage: 'Storage',
  audio: 'Audio',
  motor: 'Motor Control',
  timing: 'RTC / Timing',
  misc: 'Miscellaneous',
};
