import type { HardwareComponent, BoardGpioPin } from './designerTypes'

// ═══════════════════════════════════════════════════════════════════════════════
//  COMPONENT CATALOG — 68 components matching backend LibraryCatalog.java
// ═══════════════════════════════════════════════════════════════════════════════

export const COMPONENT_CATALOG: HardwareComponent[] = [

  // ─── SENSORS (21) ──────────────────────────────────────────────────

  {
    id: 'dht22', label: 'DHT22', displayName: 'DHT22 Temperature & Humidity',
    category: 'sensor', icon: 'Thermometer',
    description: 'Digital temperature and humidity sensor. ±0.5°C, ±2% RH accuracy.',
    educationTip: 'Sends temperature and humidity as digital pulses on one wire — like Morse code for weather data! The Arduino library decodes these pulses automatically.',
    estimatedCostUsd: 4.00, whereToBuy: ['Amazon', 'AliExpress', 'Adafruit'],
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'dht11', label: 'DHT11', displayName: 'DHT11 Temperature & Humidity',
    category: 'sensor', icon: 'Thermometer',
    description: 'Basic digital temp/humidity sensor. ±2°C accuracy. Lower cost than DHT22.',
    educationTip: 'Same idea as DHT22 but cheaper and less accurate. Perfect for learning — in real projects you\'d upgrade to DHT22 once you know it works!',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'bme280', label: 'BME280', displayName: 'BME280 Temp + Humidity + Pressure',
    category: 'sensor', icon: 'Wind',
    description: 'High-accuracy I2C environmental sensor. Measures temperature, humidity, and barometric pressure.',
    educationTip: 'Uses I2C — a smart protocol where two wires can connect up to 127 sensors. SDA carries data, SCL is the clock tick that keeps everything in sync.',
    estimatedCostUsd: 3.50, whereToBuy: ['Amazon', 'AliExpress', 'Adafruit'],
    voltageWarning: '3.3V only! Use a logic level converter if your board is 5V.',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'bmp280', label: 'BMP280', displayName: 'BMP280 Temperature & Pressure',
    category: 'sensor', icon: 'Gauge',
    description: 'Temperature and barometric pressure sensor via I2C. No humidity.',
    educationTip: 'Measures air pressure which changes with altitude — you can calculate your height above sea level! Every 12 meters up ≈ 1 hPa less pressure.',
    estimatedCostUsd: 2.50, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: '3.3V only.',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'soil_moisture', label: 'Soil Moisture', displayName: 'Capacitive Soil Moisture Sensor',
    category: 'sensor', icon: 'Droplets',
    description: 'Capacitive moisture sensor. No corrosion. Outputs analog voltage proportional to moisture.',
    educationTip: 'Measures how much water is in soil by detecting tiny electrical capacitance changes — the same physics as a touchscreen detecting your finger!',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'aout', label: 'AOUT', type: 'analog',  side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'mq2', label: 'MQ-2', displayName: 'MQ-2 Gas & Smoke Sensor',
    category: 'sensor', icon: 'AlertTriangle',
    description: 'Detects smoke, LPG, methane, hydrogen. Analog + digital threshold output.',
    educationTip: 'A heating element inside burns gas molecules, changing electrical resistance. This is the same principle used in industrial gas detectors in factories and mines!',
    estimatedCostUsd: 2.50, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: 'Requires 5V for heater. Use voltage divider on analog output for 3.3V boards.',
    pins: [
      { id: 'aout', label: 'AOUT', type: 'analog',  side: 'right', required: true },
      { id: 'dout', label: 'DOUT', type: 'digital',  side: 'right', required: false },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'mpu6050', label: 'MPU-6050', displayName: 'MPU-6050 Accelerometer + Gyroscope',
    category: 'sensor', icon: 'Activity',
    description: '6-axis IMU. 3-axis accelerometer + 3-axis gyroscope via I2C.',
    educationTip: 'Your phone uses the exact same type of sensor to know which way it\'s tilted! The accelerometer measures forces (like gravity), the gyroscope measures rotation speed.',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: '3.3V logic. Use level shifter with 5V boards.',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',     side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',     side: 'right', required: true },
      { id: 'int', label: 'INT', type: 'digital',  side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power',    side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'hcsr04', label: 'HC-SR04', displayName: 'HC-SR04 Ultrasonic Distance',
    category: 'sensor', icon: 'Radar',
    description: 'Ultrasonic distance sensor. Range 2cm–400cm. Accuracy ±3mm.',
    educationTip: 'Works exactly like bat echolocation! Sends a burst of ultrasound, then measures how long it takes to bounce back. Distance = speed of sound × time ÷ 2.',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: 'ECHO pin outputs 5V. Use 1kΩ+2kΩ voltage divider for 3.3V boards.',
    pins: [
      { id: 'trig', label: 'TRIG', type: 'digital', side: 'right', required: true },
      { id: 'echo', label: 'ECHO', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'pir', label: 'PIR HC-SR501', displayName: 'PIR Motion Sensor (HC-SR501)',
    category: 'sensor', icon: 'Eye',
    description: 'Passive infrared motion detector. Adjustable sensitivity and hold time.',
    educationTip: 'Detects heat radiation (infrared) from warm bodies. It\'s in almost every automatic light and security camera you\'ve ever walked past!',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'out', label: 'OUT', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'ldr', label: 'LDR', displayName: 'LDR Photoresistor',
    category: 'sensor', icon: 'Sun',
    description: 'Light-dependent resistor. Resistance drops as light increases.',
    educationTip: 'Made from cadmium sulfide — a material where light knocks electrons loose, reducing resistance. No library needed — just read the analog voltage!',
    estimatedCostUsd: 0.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'aout', label: 'OUT', type: 'analog',  side: 'right', required: true },
      { id: 'gnd',  label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'bh1750', label: 'BH1750', displayName: 'BH1750 Ambient Light Sensor',
    category: 'sensor', icon: 'Sun',
    description: 'Digital light sensor, outputs lux values via I2C. Range 1–65535 lux.',
    educationTip: 'Measures in lux — the unit photographers use. 0 lux = total darkness, 100,000 lux = direct sunlight. Your phone uses the same unit to adjust screen brightness!',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'vl53l0x', label: 'VL53L0X', displayName: 'VL53L0X ToF Laser Distance',
    category: 'sensor', icon: 'Crosshair',
    description: 'Laser time-of-flight distance, up to 2m. I2C. Much more accurate than HC-SR04.',
    educationTip: 'Fires a tiny invisible laser and measures how long light takes to bounce back. Light travels 300,000 km/s — the math is mind-blowing!',
    estimatedCostUsd: 5.00, whereToBuy: ['Adafruit', 'Amazon'],
    voltageWarning: '3.3V only.',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'max30102', label: 'MAX30102', displayName: 'MAX30102 Heart Rate & SpO2',
    category: 'sensor', icon: 'Heart',
    description: 'Optical heart rate and blood oxygen sensor via I2C. Used in fitness trackers.',
    educationTip: 'Shines red and infrared LEDs through your fingertip. Oxygenated blood absorbs different wavelengths — by measuring absorption, it calculates your pulse!',
    estimatedCostUsd: 4.00, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: '3.3V only.',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',     side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',     side: 'right', required: true },
      { id: 'int', label: 'INT', type: 'digital',  side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power',    side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'ds18b20', label: 'DS18B20', displayName: 'DS18B20 Waterproof Temperature',
    category: 'sensor', icon: 'Thermometer',
    description: 'Waterproof 1-Wire temperature sensor. ±0.5°C. Multiple sensors on one pin.',
    educationTip: 'Uses the 1-Wire protocol — you can chain up to 127 DS18B20 sensors on a single wire! Each has a unique 64-bit address burned in at the factory.',
    estimatedCostUsd: 3.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'hx711', label: 'HX711', displayName: 'HX711 Load Cell Amplifier',
    category: 'sensor', icon: 'Scale',
    description: '24-bit ADC for weight/force measurement with load cell. Used in digital scales.',
    educationTip: 'A load cell bends slightly under weight. Strain gauges measure the bend. HX711 amplifies the tiny signal to readable levels!',
    estimatedCostUsd: 2.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'dout', label: 'DOUT', type: 'digital', side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'ina219', label: 'INA219', displayName: 'INA219 Current & Voltage Sensor',
    category: 'sensor', icon: 'Zap',
    description: 'Measures DC current and voltage via I2C. Up to 3.2A, 26V.',
    educationTip: 'Measures voltage across a tiny shunt resistor using Ohm\'s Law (V = IR). Since resistance is known, current = voltage ÷ resistance.',
    estimatedCostUsd: 3.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'rain_sensor', label: 'Rain Sensor', displayName: 'Rain / Water Detection Sensor',
    category: 'sensor', icon: 'CloudRain',
    description: 'Detects water/rain via conductive traces. Analog + digital output.',
    educationTip: 'Water conducts electricity slightly. When rain hits the sensor, it completes a circuit between the traces, reducing resistance.',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'aout', label: 'AOUT', type: 'analog',  side: 'right', required: true },
      { id: 'dout', label: 'DOUT', type: 'digital',  side: 'right', required: false },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'flex_sensor', label: 'Flex Sensor', displayName: 'Flex / Bend Sensor',
    category: 'sensor', icon: 'GitBranch',
    description: 'Resistance increases when bent. Used in gloves, wearables, gesture control.',
    educationTip: 'Conductive ink on plastic — bending cracks the ink slightly, increasing resistance. Same tech used in VR hand tracking!',
    estimatedCostUsd: 8.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'aout', label: 'OUT', type: 'analog',  side: 'right', required: true },
      { id: 'gnd',  label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'ads1115', label: 'ADS1115', displayName: 'ADS1115 16-bit ADC',
    category: 'sensor', icon: 'Activity',
    description: '16-bit 4-channel ADC via I2C. Far more precise than built-in 10/12-bit ADC.',
    educationTip: '16 bits = 65,536 levels vs Arduino\'s 10-bit = 1,024 levels. That\'s 64× more precision — like measuring with a ruler marked in 0.05mm instead of 3mm!',
    estimatedCostUsd: 3.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'touch_ttp223', label: 'TTP223 Touch', displayName: 'TTP223 Capacitive Touch Sensor',
    category: 'sensor', icon: 'Fingerprint',
    description: 'Capacitive touch button. Digital output — HIGH when touched.',
    educationTip: 'Detects the tiny electrical charge in your finger through a pad. Same capacitive sensing as your phone screen — just simpler!',
    estimatedCostUsd: 0.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'out', label: 'OUT', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'hall_effect', label: 'Hall Effect', displayName: 'Hall Effect Magnetic Sensor',
    category: 'sensor', icon: 'Magnet',
    description: 'Detects magnetic fields. Digital output toggles near a magnet.',
    educationTip: 'When a magnetic field passes through a semiconductor, it pushes electrons to one side (Lorentz force), creating a voltage. Used in door sensors and RPM counters!',
    estimatedCostUsd: 0.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'out', label: 'OUT', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },

  // ─── DISPLAYS (7) ─────────────────────────────────────────────────

  {
    id: 'ssd1306', label: 'SSD1306 OLED', displayName: 'SSD1306 OLED Display 0.96"',
    category: 'display', icon: 'Monitor',
    description: '128×64 pixel OLED display via I2C. 0.96 inch. No backlight needed.',
    educationTip: 'OLED pixels emit their own light — each pixel is a microscopic LED. Black pixels use zero power, which is why OLED phones have better battery life!',
    estimatedCostUsd: 3.50, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: '3.3V only.',
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'lcd_i2c', label: 'LCD 16×2 I2C', displayName: 'LCD 16×2 with I2C Backpack',
    category: 'display', icon: 'AlignLeft',
    description: 'Classic 16-character × 2-line LCD with I2C adapter. Only 4 wires needed.',
    educationTip: 'Without the I2C backpack this needs 16 wires! The I2C chip (PCF8574) converts 2-wire signals into the 8-bit parallel signal the LCD needs.',
    estimatedCostUsd: 3.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'st7789', label: 'ST7789 TFT', displayName: 'ST7789 TFT Color Display 1.3"',
    category: 'display', icon: 'Tablet',
    description: '240×240 color TFT display via SPI. Full RGB, 1.3 inch.',
    educationTip: 'SPI can transfer data much faster than I2C — this display needs speed to refresh all 57,600 pixels fast enough for smooth graphics.',
    estimatedCostUsd: 6.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'mosi', label: 'MOSI', type: 'spi',     side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'spi',     side: 'right', required: true },
      { id: 'cs',   label: 'CS',   type: 'spi',     side: 'right', required: true },
      { id: 'dc',   label: 'DC',   type: 'digital',  side: 'right', required: true },
      { id: 'rst',  label: 'RST',  type: 'digital',  side: 'right', required: false },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'epaper_2in9', label: 'E-Paper 2.9"', displayName: 'E-Paper Display 2.9"',
    category: 'display', icon: 'FileText',
    description: '296×128 e-ink display via SPI. Extremely low power — holds image without power.',
    educationTip: 'E-ink pixels are tiny capsules of black and white charged particles. Electricity moves them into position, then the image stays with ZERO power. Like a whiteboard that remembers!',
    estimatedCostUsd: 18.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'mosi', label: 'MOSI', type: 'spi',     side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'spi',     side: 'right', required: true },
      { id: 'cs',   label: 'CS',   type: 'spi',     side: 'right', required: true },
      { id: 'dc',   label: 'DC',   type: 'digital',  side: 'right', required: true },
      { id: 'rst',  label: 'RST',  type: 'digital',  side: 'right', required: true },
      { id: 'busy', label: 'BUSY', type: 'digital',  side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'ili9341', label: 'ILI9341 TFT', displayName: 'ILI9341 2.4" TFT Color Display',
    category: 'display', icon: 'Tv',
    description: '320×240 SPI color TFT. Touchscreen-compatible. Great for dashboards.',
    educationTip: 'With 76,800 pixels each needing 2 bytes of color data, one full frame is 150KB. SPI runs at up to 80MHz to push that data fast enough for animations!',
    estimatedCostUsd: 8.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'mosi', label: 'MOSI', type: 'spi',     side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'spi',     side: 'right', required: true },
      { id: 'cs',   label: 'CS',   type: 'spi',     side: 'right', required: true },
      { id: 'dc',   label: 'DC',   type: 'digital',  side: 'right', required: true },
      { id: 'rst',  label: 'RST',  type: 'digital',  side: 'right', required: false },
      { id: 'miso', label: 'MISO', type: 'spi',     side: 'right', required: false },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'seven_segment', label: '7-Segment', displayName: '4-Digit 7-Segment Display (TM1637)',
    category: 'display', icon: 'Hash',
    description: '4-digit LED display driven by TM1637. Great for clocks and counters.',
    educationTip: 'Each digit has 7 LED segments (hence the name). The TM1637 chip multiplexes — it lights one digit at a time so fast your eyes see all four lit simultaneously!',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'clk',  label: 'CLK',  type: 'digital', side: 'right', required: true },
      { id: 'dio',  label: 'DIO',  type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'max7219', label: 'MAX7219 Matrix', displayName: 'MAX7219 8×8 LED Matrix',
    category: 'display', icon: 'LayoutGrid',
    description: 'SPI-driven 8×8 LED matrix. Chainable for scrolling text displays.',
    educationTip: 'The MAX7219 chip handles all 64 LEDs with multiplexing — only 3 data wires needed instead of 64! Chain multiple matrices for scrolling marquee signs.',
    estimatedCostUsd: 3.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'din', label: 'DIN', type: 'spi',    side: 'right', required: true },
      { id: 'cs',  label: 'CS',  type: 'spi',    side: 'right', required: true },
      { id: 'clk', label: 'CLK', type: 'spi',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },

  // ─── ACTUATORS (7) ────────────────────────────────────────────────

  {
    id: 'relay', label: 'Relay Module', displayName: 'Relay Module (Single Channel)',
    category: 'actuator', icon: 'Zap',
    description: 'Electrically-controlled switch. Controls mains voltage devices safely.',
    educationTip: 'Your tiny 3.3V signal magnetizes a coil, which physically moves a metal arm to switch 240V mains. Never touch the mains side yourself!',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'in',  label: 'IN',  type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'led', label: 'LED', displayName: 'LED (Single)',
    category: 'actuator', icon: 'Lightbulb',
    description: 'Single LED indicator. Needs 220Ω–1kΩ current-limiting resistor.',
    educationTip: 'LED = Light Emitting Diode. The resistor is critical — without it, too much current flows and the LED burns out in milliseconds!',
    estimatedCostUsd: 0.10, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'anode',   label: 'ANODE (+)', type: 'digital', side: 'right', required: true },
      { id: 'cathode', label: 'GND (-)',   type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'neopixel', label: 'NeoPixel Strip', displayName: 'NeoPixel RGB LED Strip (WS2812)',
    category: 'actuator', icon: 'Sparkles',
    description: 'Individually addressable RGB LEDs. One wire controls 1–300 LEDs.',
    educationTip: 'Each NeoPixel has its own tiny microcontroller inside! You send a chain of color data, each pixel reads its 3-byte RGB portion and passes the rest along.',
    estimatedCostUsd: 8.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'buzzer', label: 'Buzzer', displayName: 'Passive Buzzer',
    category: 'actuator', icon: 'Volume2',
    description: 'PWM-driven buzzer. Can play tones and simple melodies.',
    educationTip: 'PWM switches the buzzer on/off thousands of times per second. 440Hz = musical note A4. Change the frequency and you change the pitch — music with math!',
    estimatedCostUsd: 0.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'pwm', label: 'PWM', type: 'pwm',    side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'laser_module', label: 'Laser', displayName: 'KY-008 Laser Module',
    category: 'actuator', icon: 'Crosshair',
    description: '650nm red laser diode module. 5mW. For tripwires, distance measurement.',
    educationTip: 'A laser diode emits coherent light — all waves in phase and same wavelength. Unlike an LED\'s broad beam, laser light barely spreads over distance. Great for precision targeting!',
    estimatedCostUsd: 1.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'sig', label: 'SIG', type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'solenoid_valve', label: 'Solenoid Valve', displayName: '12V Solenoid Valve',
    category: 'actuator', icon: 'Pipette',
    description: 'Electrically-controlled water valve. Use relay or MOSFET to drive.',
    educationTip: 'A coil creates a magnetic field that pulls a plunger, opening the valve. Same principle as a doorbell — but instead of ringing, it lets water flow!',
    estimatedCostUsd: 5.00, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: 'Requires 12V and relay/MOSFET. Never connect directly to GPIO.',
    pins: [
      { id: 'ctrl', label: 'CTRL', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'water_pump', label: 'Water Pump', displayName: 'Mini Water Pump (3-6V)',
    category: 'actuator', icon: 'Waves',
    description: 'Submersible mini pump. 120L/h flow. Use MOSFET or relay to control.',
    educationTip: 'A DC motor spins an impeller that pushes water outward via centrifugal force. Control speed with PWM through a MOSFET!',
    estimatedCostUsd: 3.00, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: 'Never connect directly to GPIO pin — use MOSFET or relay.',
    pins: [
      { id: 'ctrl', label: 'CTRL', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },

  // ─── MOTORS (6) ───────────────────────────────────────────────────

  {
    id: 'servo', label: 'SG90 Servo', displayName: 'SG90 Micro Servo Motor',
    category: 'motor', icon: 'RotateCcw',
    description: '180° servo motor. PWM-controlled. Torque: 1.8 kg·cm.',
    educationTip: 'Inside: motor + gearbox + feedback potentiometer. PWM pulse duration tells it the angle — 1ms=0°, 1.5ms=90°, 2ms=180°. Position control through time!',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'pwm', label: 'PWM', type: 'pwm',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'l298n', label: 'L298N Motor', displayName: 'L298N Dual DC Motor Driver',
    category: 'motor', icon: 'Cog',
    description: 'Dual H-bridge driver. Controls 2 DC motors — direction + speed via PWM.',
    educationTip: 'An H-bridge has 4 transistors in an "H" shape. Activate different pairs to reverse motor direction. PWM controls speed by rapidly switching power on/off.',
    estimatedCostUsd: 2.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'in1', label: 'IN1', type: 'digital', side: 'right', required: true },
      { id: 'in2', label: 'IN2', type: 'digital', side: 'right', required: true },
      { id: 'ena', label: 'ENA', type: 'pwm',     side: 'right', required: false },
      { id: 'in3', label: 'IN3', type: 'digital',  side: 'right', required: false },
      { id: 'in4', label: 'IN4', type: 'digital',  side: 'right', required: false },
      { id: 'enb', label: 'ENB', type: 'pwm',     side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'stepper_a4988', label: 'A4988 Stepper', displayName: 'A4988 Stepper Motor Driver',
    category: 'motor', icon: 'Settings',
    description: 'Microstepping stepper motor driver. STEP/DIR interface. Up to 2A.',
    educationTip: 'Stepper motors move in precise fixed steps — 200 steps = 360°. CNC machines use this for 0.1mm positioning accuracy. Microstepping divides each step further!',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'step', label: 'STEP', type: 'digital', side: 'right', required: true },
      { id: 'dir',  label: 'DIR',  type: 'digital', side: 'right', required: true },
      { id: 'en',   label: 'EN',   type: 'digital', side: 'right', required: false },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'pca9685', label: 'PCA9685', displayName: 'PCA9685 16-Channel PWM Driver',
    category: 'motor', icon: 'Sliders',
    description: '16-channel 12-bit PWM driver via I2C. Controls 16 servos from 2 pins.',
    educationTip: 'One I2C chip gives you 16 independent PWM channels — run 16 servos from just 2 wires! Stack up to 62 boards for 992 channels.',
    estimatedCostUsd: 4.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'tmc2209', label: 'TMC2209', displayName: 'TMC2209 Silent Stepper Driver',
    category: 'motor', icon: 'Settings',
    description: 'Ultra-quiet stepper driver with UART config. StealthChop for silent operation.',
    educationTip: 'TMC2209 uses StealthChop — a special PWM algorithm that makes stepper motors nearly silent. Regular drivers make a loud whine. This is the tech behind silent 3D printers!',
    estimatedCostUsd: 5.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'step', label: 'STEP', type: 'digital', side: 'right', required: true },
      { id: 'dir',  label: 'DIR',  type: 'digital', side: 'right', required: true },
      { id: 'en',   label: 'EN',   type: 'digital', side: 'right', required: false },
      { id: 'rx',   label: 'RX',   type: 'uart',    side: 'right', required: false },
      { id: 'tx',   label: 'TX',   type: 'uart',    side: 'right', required: false },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'encoder', label: 'Rotary Encoder', displayName: 'Rotary Encoder (Motor)',
    category: 'motor', icon: 'CircleDot',
    description: 'Optical/magnetic rotary encoder for motor feedback. Quadrature output.',
    educationTip: 'Two outputs (A, B) switch as the shaft turns. By detecting which leads, you know direction. Counting pulses gives exact position — essential for robotics closed-loop control!',
    estimatedCostUsd: 3.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'clk', label: 'A/CLK', type: 'digital', side: 'right', required: true },
      { id: 'dt',  label: 'B/DT',  type: 'digital', side: 'right', required: true },
      { id: 'vcc', label: 'VCC',   type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND',   type: 'ground',  side: 'right', required: true },
    ],
  },

  // ─── COMMUNICATION (11) ───────────────────────────────────────────

  {
    id: 'wifi', label: 'WiFi', displayName: 'WiFi (ESP32 Built-in)',
    category: 'communication', icon: 'Wifi',
    description: 'ESP32 built-in WiFi. No external module needed.',
    educationTip: 'WiFi uses 2.4GHz radio waves — same frequency as your microwave oven! The ESP32 has a full TCP/IP stack, meaning it speaks the same protocol as every website.',
    estimatedCostUsd: 0, whereToBuy: [],
    pins: [],
  },
  {
    id: 'ble', label: 'BLE', displayName: 'Bluetooth Low Energy (ESP32 Built-in)',
    category: 'communication', icon: 'Bluetooth',
    description: 'ESP32 built-in BLE. Perfect for phone connectivity.',
    educationTip: 'BLE uses tiny bursts of data — a sensor can run for years on a coin cell battery. Your fitness tracker uses BLE to sync with your phone!',
    estimatedCostUsd: 0, whereToBuy: [],
    pins: [],
  },
  {
    id: 'mqtt', label: 'MQTT', displayName: 'MQTT Client (over WiFi)',
    category: 'communication', icon: 'MessageSquare',
    description: 'MQTT pub/sub messaging protocol over WiFi. Standard IoT protocol.',
    educationTip: 'MQTT uses publish/subscribe — devices send messages to "topics" and others subscribe to receive them. Like a group chat where each topic is a channel!',
    estimatedCostUsd: 0, whereToBuy: [],
    pins: [],
  },
  {
    id: 'espnow', label: 'ESP-NOW', displayName: 'ESP-NOW Protocol (ESP32 Built-in)',
    category: 'communication', icon: 'Radio',
    description: 'ESP-NOW peer-to-peer protocol. No router needed. Up to 250 bytes, <1ms latency.',
    educationTip: 'ESP-NOW lets ESP32s talk directly to each other without WiFi — like walkie-talkies for microcontrollers. Ultra-fast and perfect for real-time control!',
    estimatedCostUsd: 0, whereToBuy: [],
    pins: [],
  },
  {
    id: 'hc05', label: 'HC-05 BT', displayName: 'HC-05 Bluetooth Module',
    category: 'communication', icon: 'Bluetooth',
    description: 'Classic Bluetooth 2.0 serial bridge. Pairs with phone/PC for wireless serial.',
    educationTip: 'Bluetooth at 2.4GHz replaces a serial cable with radio waves. The HC-05 converts UART bytes into Bluetooth signals — a cable eliminator in chip form!',
    estimatedCostUsd: 4.00, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: 'RX pin is 3.3V max. Use 1kΩ+2kΩ divider from 5V TX.',
    pins: [
      { id: 'tx',  label: 'TX',  type: 'uart',   side: 'right', required: true },
      { id: 'rx',  label: 'RX',  type: 'uart',   side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'gps_neo6m', label: 'NEO-6M GPS', displayName: 'NEO-6M GPS Module',
    category: 'communication', icon: 'MapPin',
    description: 'GPS receiver. NMEA sentences via UART. 3.5m accuracy.',
    educationTip: 'Listens to 4+ satellites at 20,000km. By comparing tiny time differences in signals travelling at light speed, it triangulates your position. Relativistic physics in a $5 chip!',
    estimatedCostUsd: 5.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'tx',  label: 'TX',  type: 'uart',   side: 'right', required: true },
      { id: 'rx',  label: 'RX',  type: 'uart',   side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'can_bus', label: 'MCP2515 CAN', displayName: 'MCP2515 CAN Bus Module',
    category: 'communication', icon: 'Network',
    description: 'CAN bus controller with SPI interface. For automotive OBD2 and industrial networks.',
    educationTip: 'CAN bus connects every ECU in your car — engine, brakes, airbags — on just 2 wires. Your project can now speak the same language as a BMW!',
    estimatedCostUsd: 3.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'mosi', label: 'MOSI', type: 'spi',     side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi',     side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'spi',     side: 'right', required: true },
      { id: 'cs',   label: 'CS',   type: 'spi',     side: 'right', required: true },
      { id: 'int',  label: 'INT',  type: 'digital',  side: 'right', required: false },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'lorawan', label: 'LoRa SX1278', displayName: 'LoRa SX1278 Long Range Radio',
    category: 'communication', icon: 'Radio',
    description: 'Long-range radio module. Up to 10km range, ultra-low power. SPI interface.',
    educationTip: 'LoRa sends tiny packets up to 10km using chirp spread spectrum. IoT sensors in remote farms, flood monitors — this is the radio that connects them!',
    estimatedCostUsd: 5.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'mosi', label: 'MOSI', type: 'spi',     side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi',     side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'spi',     side: 'right', required: true },
      { id: 'cs',   label: 'CS',   type: 'spi',     side: 'right', required: true },
      { id: 'rst',  label: 'RST',  type: 'digital',  side: 'right', required: true },
      { id: 'dio0', label: 'DIO0', type: 'digital',  side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'rs485', label: 'MAX485 RS-485', displayName: 'MAX485 RS-485 / Modbus Module',
    category: 'communication', icon: 'Cable',
    description: 'RS-485 transceiver for Modbus industrial networks. Up to 1200m cable length.',
    educationTip: 'RS-485 uses differential signaling — two wires carry opposite voltages. Noise affects both equally, the receiver subtracts them, cancelling the noise. Perfect for factories!',
    estimatedCostUsd: 1.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'tx',  label: 'TX',  type: 'uart',    side: 'right', required: true },
      { id: 'rx',  label: 'RX',  type: 'uart',    side: 'right', required: true },
      { id: 'de',  label: 'DE',  type: 'digital',  side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',    side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'rfid_rc522', label: 'RC522 RFID', displayName: 'RC522 RFID Reader/Writer',
    category: 'communication', icon: 'CreditCard',
    description: 'RFID reader/writer at 13.56MHz via SPI. Works with MIFARE cards and fobs.',
    educationTip: 'The reader creates a magnetic field. A card\'s tiny antenna absorbs energy and sends back its ID. No battery in the card — wireless power transfer! (NFC uses the same idea.)',
    estimatedCostUsd: 2.50, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: '3.3V only.',
    pins: [
      { id: 'mosi', label: 'MOSI',   type: 'spi',     side: 'right', required: true },
      { id: 'miso', label: 'MISO',   type: 'spi',     side: 'right', required: true },
      { id: 'sck',  label: 'SCK',    type: 'spi',     side: 'right', required: true },
      { id: 'sda',  label: 'SDA/CS', type: 'spi',     side: 'right', required: true },
      { id: 'rst',  label: 'RST',    type: 'digital',  side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',    type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',    type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'nrf24l01', label: 'NRF24L01', displayName: 'NRF24L01 2.4GHz Radio',
    category: 'communication', icon: 'Radio',
    description: '2.4GHz radio transceiver. Up to 100m range. SPI interface. Multi-node mesh capable.',
    educationTip: 'Creates its own mini wireless network — up to 6 nodes can talk simultaneously. Much simpler than WiFi but perfect for remote controls and sensor networks!',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: '3.3V only! 5V will destroy it.',
    pins: [
      { id: 'mosi', label: 'MOSI', type: 'spi',     side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi',     side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'spi',     side: 'right', required: true },
      { id: 'cs',   label: 'CSN',  type: 'spi',     side: 'right', required: true },
      { id: 'ce',   label: 'CE',   type: 'digital',  side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',    side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',   side: 'right', required: true },
    ],
  },

  // ─── STORAGE (3) ──────────────────────────────────────────────────

  {
    id: 'sd_card', label: 'SD Card', displayName: 'MicroSD Card Module',
    category: 'storage', icon: 'HardDrive',
    description: 'MicroSD card reader via SPI. Store logs, configs, audio files.',
    educationTip: 'SD cards use SPI — a fast 4-wire protocol where master and slave exchange data simultaneously. FAT32 filesystem — same as your USB drive!',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    voltageWarning: '3.3V only for data pins.',
    pins: [
      { id: 'mosi', label: 'MOSI', type: 'spi',    side: 'right', required: true },
      { id: 'miso', label: 'MISO', type: 'spi',    side: 'right', required: true },
      { id: 'sck',  label: 'SCK',  type: 'spi',    side: 'right', required: true },
      { id: 'cs',   label: 'CS',   type: 'spi',    side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'eeprom', label: 'EEPROM 24C256', displayName: '24C256 EEPROM (32KB)',
    category: 'storage', icon: 'Save',
    description: 'I2C EEPROM. 32KB non-volatile storage. Survives power off.',
    educationTip: 'EEPROM = Electrically Erasable Programmable Read-Only Memory. Each byte can be written ~1 million times and remembered forever without power!',
    estimatedCostUsd: 1.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'littlefs', label: 'LittleFS', displayName: 'LittleFS (Built-in Flash Storage)',
    category: 'storage', icon: 'Database',
    description: 'Flash filesystem built into ESP32. Store files without extra hardware.',
    educationTip: 'LittleFS uses the ESP32\'s unused flash memory as a tiny hard drive. Wear-leveling spreads writes evenly so no single cell wears out first. Smart!',
    estimatedCostUsd: 0, whereToBuy: [],
    pins: [],
  },

  // ─── AUDIO (3) ────────────────────────────────────────────────────

  {
    id: 'i2s_dac', label: 'MAX98357 I2S', displayName: 'MAX98357 I2S Audio Amplifier',
    category: 'audio', icon: 'Music',
    description: 'I2S DAC + Class D amplifier. Drives 3W speaker directly from digital audio.',
    educationTip: 'I2S carries digital audio as binary numbers. The MAX98357 converts numbers to analog voltage thousands of times per second — fast enough to reproduce sound!',
    estimatedCostUsd: 6.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'bclk', label: 'BCLK', type: 'digital', side: 'right', required: true },
      { id: 'lrc',  label: 'LRC',  type: 'digital', side: 'right', required: true },
      { id: 'din',  label: 'DIN',  type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'dfplayer', label: 'DFPlayer', displayName: 'DFPlayer Mini MP3 Player',
    category: 'audio', icon: 'Disc',
    description: 'Standalone MP3 player with SD card. UART control. Built-in amplifier.',
    educationTip: 'A complete MP3 decoder in a tiny chip — reads files from SD card, decodes compressed audio, and drives a speaker. Send simple serial commands like "play track 3"!',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'rx',  label: 'RX',  type: 'uart',   side: 'right', required: true },
      { id: 'tx',  label: 'TX',  type: 'uart',   side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'microphone_max9814', label: 'MAX9814 Mic', displayName: 'MAX9814 Electret Microphone',
    category: 'audio', icon: 'Mic',
    description: 'Amplified microphone with AGC. Analog output for sound detection and recording.',
    educationTip: 'Sound waves vibrate a thin membrane which changes capacitance in the electret element. The MAX9814 amplifies this tiny signal and automatically adjusts gain — loud sounds don\'t clip!',
    estimatedCostUsd: 4.00, whereToBuy: ['Adafruit', 'Amazon'],
    pins: [
      { id: 'out', label: 'OUT', type: 'analog', side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',  side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground', side: 'right', required: true },
    ],
  },

  // ─── TIMING (3) ───────────────────────────────────────────────────

  {
    id: 'ds3231', label: 'DS3231 RTC', displayName: 'DS3231 Real Time Clock',
    category: 'timing', icon: 'Clock',
    description: 'Extremely accurate RTC via I2C. Keeps time when powered off via coin cell.',
    educationTip: 'Has a temperature-compensated crystal oscillator — adjusts speed based on temperature. Loses only 1 second per week! Compare to Arduino: ~1 second per hour.',
    estimatedCostUsd: 2.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',     side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',     side: 'right', required: true },
      { id: 'sqw', label: 'SQW', type: 'digital',  side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power',    side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',   side: 'right', required: true },
    ],
  },
  {
    id: 'ds1307_rtc', label: 'DS1307 RTC', displayName: 'DS1307 Real Time Clock',
    category: 'timing', icon: 'Clock',
    description: 'Basic RTC via I2C with battery backup. Less accurate than DS3231 but cheaper.',
    educationTip: 'Uses a 32.768kHz crystal — divide by 2 fifteen times (2^15 = 32768) and you get exactly 1 tick per second. The same crystal frequency used in quartz watches since 1969!',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'sda', label: 'SDA', type: 'i2c',    side: 'right', required: true },
      { id: 'scl', label: 'SCL', type: 'i2c',    side: 'right', required: true },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'ntp', label: 'NTP', displayName: 'NTP Time Sync (over WiFi)',
    category: 'timing', icon: 'Clock',
    description: 'Network Time Protocol syncs clock from internet time servers.',
    educationTip: 'NTP contacts atomic clock servers via the internet. Accurate to ~10 milliseconds. Free and always available — but only when WiFi is connected!',
    estimatedCostUsd: 0, whereToBuy: [],
    pins: [],
  },

  // ─── MISC / INPUT (7) ────────────────────────────────────────────

  {
    id: 'push_button', label: 'Push Button', displayName: 'Momentary Push Button',
    category: 'misc', icon: 'CircleDot',
    description: 'Momentary push button. Use INPUT_PULLUP to avoid external resistor.',
    educationTip: 'When pressed, connects two pins. Using INPUT_PULLUP means the Arduino\'s internal 20kΩ resistor holds the pin HIGH until you press it to GND. No external parts needed!',
    estimatedCostUsd: 0.10, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'out', label: 'OUT', type: 'digital', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'potentiometer', label: 'Potentiometer', displayName: 'Rotary Potentiometer',
    category: 'misc', icon: 'SlidersHorizontal',
    description: 'Variable resistor. Analog output 0V to VCC as you turn the dial.',
    educationTip: 'A sliding contact moves along a resistor wire. Turn it: resistance changes, voltage follows Ohm\'s Law. One of the oldest electronic components still in use!',
    estimatedCostUsd: 0.30, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'aout', label: 'OUT', type: 'analog', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC', type: 'power',  side: 'right', required: true },
      { id: 'gnd',  label: 'GND', type: 'ground', side: 'right', required: true },
    ],
  },
  {
    id: 'rotary_encoder', label: 'Rotary Encoder', displayName: 'Rotary Encoder (KY-040)',
    category: 'misc', icon: 'RefreshCw',
    description: 'Infinite rotation encoder with click. Quadrature pulses for direction + speed.',
    educationTip: 'Two outputs (A, B) switch as you turn. If A leads B: clockwise. If B leads A: counter-clockwise. Count pulses to know exactly how far it turned!',
    estimatedCostUsd: 1.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'clk', label: 'CLK', type: 'digital', side: 'right', required: true },
      { id: 'dt',  label: 'DT',  type: 'digital', side: 'right', required: true },
      { id: 'sw',  label: 'SW',  type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'joystick', label: 'Joystick', displayName: 'Analog Joystick Module (KY-023)',
    category: 'misc', icon: 'Gamepad2',
    description: 'Dual-axis analog joystick with push button. 2 analog + 1 digital output.',
    educationTip: 'Two potentiometers on perpendicular axes. Push the stick and you get X/Y coordinates from 0 to 1023. Same basic mechanism as your game controller thumbstick!',
    estimatedCostUsd: 1.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'vrx', label: 'VRX', type: 'analog',  side: 'right', required: true },
      { id: 'vry', label: 'VRY', type: 'analog',  side: 'right', required: true },
      { id: 'sw',  label: 'SW',  type: 'digital', side: 'right', required: false },
      { id: 'vcc', label: 'VCC', type: 'power',   side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'keypad', label: 'Keypad 4×4', displayName: '4×4 Matrix Keypad',
    category: 'misc', icon: 'Grid3x3',
    description: 'Matrix keypad with 16 keys. Only 8 GPIO pins needed.',
    educationTip: 'A 4×4 grid normally needs 16 pins. Matrix scanning sends voltage down each row and reads columns — only 8 wires for 16 buttons! This is how your laptop keyboard works too.',
    estimatedCostUsd: 2.00, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'r1', label: 'R1', type: 'digital', side: 'right', required: true },
      { id: 'r2', label: 'R2', type: 'digital', side: 'right', required: true },
      { id: 'r3', label: 'R3', type: 'digital', side: 'right', required: true },
      { id: 'r4', label: 'R4', type: 'digital', side: 'right', required: true },
      { id: 'c1', label: 'C1', type: 'digital', side: 'right', required: true },
      { id: 'c2', label: 'C2', type: 'digital', side: 'right', required: true },
      { id: 'c3', label: 'C3', type: 'digital', side: 'right', required: true },
      { id: 'c4', label: 'C4', type: 'digital', side: 'right', required: true },
    ],
  },
  {
    id: 'ir_remote', label: 'IR Receiver', displayName: 'IR Receiver (VS1838B)',
    category: 'misc', icon: 'Flashlight',
    description: 'Infrared receiver for remote control signals. 38kHz carrier.',
    educationTip: 'Your TV remote sends pulses of invisible infrared light at 38kHz. This receiver demodulates (extracts) the data signal from the carrier — like tuning a radio station!',
    estimatedCostUsd: 0.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'data', label: 'DATA', type: 'digital', side: 'right', required: true },
      { id: 'vcc',  label: 'VCC',  type: 'power',   side: 'right', required: true },
      { id: 'gnd',  label: 'GND',  type: 'ground',  side: 'right', required: true },
    ],
  },
  {
    id: 'reed_switch', label: 'Reed Switch', displayName: 'Reed Switch (Magnetic)',
    category: 'misc', icon: 'DoorOpen',
    description: 'Magnetic switch. Closes when magnet is near. Used for door/window sensors.',
    educationTip: 'Two thin metal reeds sealed in glass. A magnet makes them attract each other and touch, completing the circuit. Simple, reliable, and works through walls — perfect for door alarms!',
    estimatedCostUsd: 0.50, whereToBuy: ['Amazon', 'AliExpress'],
    pins: [
      { id: 'out', label: 'OUT', type: 'digital', side: 'right', required: true },
      { id: 'gnd', label: 'GND', type: 'ground',  side: 'right', required: true },
    ],
  },
]

// ═══════════════════════════════════════════════════════════════════════════════
//  BOARD PIN MAPS
// ═══════════════════════════════════════════════════════════════════════════════

export const BOARD_PIN_MAPS: Record<string, BoardGpioPin[]> = {

  esp32: [
    { id: 'GPIO0',  label: 'GPIO0 / BOOT',   type: 'digital', side: 'left' },
    { id: 'GPIO2',  label: 'GPIO2',           type: 'digital', side: 'left' },
    { id: 'GPIO4',  label: 'GPIO4',           type: 'digital', side: 'left' },
    { id: 'GPIO5',  label: 'GPIO5',           type: 'digital', side: 'left' },
    { id: 'GPIO12', label: 'GPIO12 / MISO',   type: 'spi',     side: 'left' },
    { id: 'GPIO13', label: 'GPIO13 / MOSI',   type: 'spi',     side: 'left' },
    { id: 'GPIO14', label: 'GPIO14 / SCK',    type: 'spi',     side: 'left' },
    { id: 'GPIO15', label: 'GPIO15 / CS',     type: 'spi',     side: 'left' },
    { id: 'GPIO16', label: 'GPIO16 / RX2',    type: 'uart',    side: 'left' },
    { id: 'GPIO17', label: 'GPIO17 / TX2',    type: 'uart',    side: 'left' },
    { id: 'GPIO18', label: 'GPIO18 / SCK',    type: 'spi',     side: 'left' },
    { id: 'GPIO19', label: 'GPIO19 / MISO',   type: 'spi',     side: 'left' },
    { id: 'GPIO21', label: 'GPIO21 / SDA',    type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GPIO22', label: 'GPIO22 / SCL',    type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GPIO23', label: 'GPIO23 / MOSI',   type: 'spi',     side: 'left' },
    { id: 'GPIO25', label: 'GPIO25 / DAC1',   type: 'analog',  side: 'left' },
    { id: 'GPIO26', label: 'GPIO26 / DAC2',   type: 'analog',  side: 'left' },
    { id: 'GPIO32', label: 'GPIO32 / ADC1_4', type: 'analog',  side: 'right' },
    { id: 'GPIO33', label: 'GPIO33 / ADC1_5', type: 'analog',  side: 'right' },
    { id: 'GPIO34', label: 'GPIO34 / ADC1_6', type: 'analog',  side: 'right' },
    { id: 'GPIO35', label: 'GPIO35 / ADC1_7', type: 'analog',  side: 'right' },
    { id: 'GPIO36', label: 'GPIO36 / VP',     type: 'analog',  side: 'right' },
    { id: 'GPIO39', label: 'GPIO39 / VN',     type: 'analog',  side: 'right' },
    { id: '3V3',    label: '3.3V',            type: 'power',   side: 'right' },
    { id: '5V',     label: 'VIN / 5V',        type: 'power',   side: 'right' },
    { id: 'GND',    label: 'GND',             type: 'ground',  side: 'right' },
  ],

  esp32_devkit_v1: [
    { id: 'GPIO0',  label: 'GPIO0 / BOOT',   type: 'digital', side: 'left' },
    { id: 'GPIO2',  label: 'GPIO2',           type: 'digital', side: 'left' },
    { id: 'GPIO4',  label: 'GPIO4',           type: 'digital', side: 'left' },
    { id: 'GPIO5',  label: 'GPIO5',           type: 'digital', side: 'left' },
    { id: 'GPIO12', label: 'GPIO12 / MISO',   type: 'spi',     side: 'left' },
    { id: 'GPIO13', label: 'GPIO13 / MOSI',   type: 'spi',     side: 'left' },
    { id: 'GPIO14', label: 'GPIO14 / SCK',    type: 'spi',     side: 'left' },
    { id: 'GPIO15', label: 'GPIO15 / CS',     type: 'spi',     side: 'left' },
    { id: 'GPIO16', label: 'GPIO16 / RX2',    type: 'uart',    side: 'left' },
    { id: 'GPIO17', label: 'GPIO17 / TX2',    type: 'uart',    side: 'left' },
    { id: 'GPIO18', label: 'GPIO18 / SCK',    type: 'spi',     side: 'left' },
    { id: 'GPIO19', label: 'GPIO19 / MISO',   type: 'spi',     side: 'left' },
    { id: 'GPIO21', label: 'GPIO21 / SDA',    type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GPIO22', label: 'GPIO22 / SCL',    type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GPIO23', label: 'GPIO23 / MOSI',   type: 'spi',     side: 'left' },
    { id: 'GPIO25', label: 'GPIO25 / DAC1',   type: 'analog',  side: 'left' },
    { id: 'GPIO26', label: 'GPIO26 / DAC2',   type: 'analog',  side: 'left' },
    { id: 'GPIO32', label: 'GPIO32 / ADC1_4', type: 'analog',  side: 'right' },
    { id: 'GPIO33', label: 'GPIO33 / ADC1_5', type: 'analog',  side: 'right' },
    { id: 'GPIO34', label: 'GPIO34 / ADC1_6', type: 'analog',  side: 'right' },
    { id: 'GPIO35', label: 'GPIO35 / ADC1_7', type: 'analog',  side: 'right' },
    { id: 'GPIO36', label: 'GPIO36 / VP',     type: 'analog',  side: 'right' },
    { id: 'GPIO39', label: 'GPIO39 / VN',     type: 'analog',  side: 'right' },
    { id: '3V3',    label: '3.3V',            type: 'power',   side: 'right' },
    { id: '5V',     label: 'VIN / 5V',        type: 'power',   side: 'right' },
    { id: 'GND',    label: 'GND',             type: 'ground',  side: 'right' },
  ],

  arduino_uno: [
    { id: 'D0',  label: 'D0 / RX',       type: 'uart',    side: 'left' },
    { id: 'D1',  label: 'D1 / TX',       type: 'uart',    side: 'left' },
    { id: 'D2',  label: 'D2 / INT0',     type: 'digital', side: 'left' },
    { id: 'D3',  label: 'D3~ / INT1',    type: 'pwm',     side: 'left' },
    { id: 'D4',  label: 'D4',            type: 'digital', side: 'left' },
    { id: 'D5',  label: 'D5~',           type: 'pwm',     side: 'left' },
    { id: 'D6',  label: 'D6~',           type: 'pwm',     side: 'left' },
    { id: 'D7',  label: 'D7',            type: 'digital', side: 'left' },
    { id: 'D8',  label: 'D8',            type: 'digital', side: 'left' },
    { id: 'D9',  label: 'D9~',           type: 'pwm',     side: 'left' },
    { id: 'D10', label: 'D10~ / SS',     type: 'spi',     side: 'left' },
    { id: 'D11', label: 'D11~ / MOSI',   type: 'spi',     side: 'left' },
    { id: 'D12', label: 'D12 / MISO',    type: 'spi',     side: 'left' },
    { id: 'D13', label: 'D13 / SCK/LED', type: 'spi',     side: 'right' },
    { id: 'A0',  label: 'A0',            type: 'analog',  side: 'right' },
    { id: 'A1',  label: 'A1',            type: 'analog',  side: 'right' },
    { id: 'A2',  label: 'A2',            type: 'analog',  side: 'right' },
    { id: 'A3',  label: 'A3',            type: 'analog',  side: 'right' },
    { id: 'A4',  label: 'A4 / SDA',      type: 'i2c',     side: 'right', i2cBus: true },
    { id: 'A5',  label: 'A5 / SCL',      type: 'i2c',     side: 'right', i2cBus: true },
    { id: '5V',  label: '5V',            type: 'power',   side: 'right' },
    { id: '3V3', label: '3.3V',          type: 'power',   side: 'right' },
    { id: 'GND', label: 'GND',           type: 'ground',  side: 'right' },
  ],

  rpi_pico: [
    { id: 'GP0',  label: 'GP0 / UART0 TX', type: 'uart',    side: 'left' },
    { id: 'GP1',  label: 'GP1 / UART0 RX', type: 'uart',    side: 'left' },
    { id: 'GP2',  label: 'GP2 / SPI0 SCK', type: 'spi',     side: 'left' },
    { id: 'GP3',  label: 'GP3 / SPI0 TX',  type: 'spi',     side: 'left' },
    { id: 'GP4',  label: 'GP4 / I2C0 SDA', type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GP5',  label: 'GP5 / I2C0 SCL', type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GP6',  label: 'GP6',            type: 'digital', side: 'left' },
    { id: 'GP7',  label: 'GP7',            type: 'digital', side: 'left' },
    { id: 'GP8',  label: 'GP8 / I2C0 SDA', type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GP9',  label: 'GP9 / I2C0 SCL', type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'GP10', label: 'GP10 / SPI1 SCK',type: 'spi',     side: 'left' },
    { id: 'GP11', label: 'GP11 / SPI1 TX', type: 'spi',     side: 'left' },
    { id: 'GP12', label: 'GP12 / SPI1 RX', type: 'spi',     side: 'right' },
    { id: 'GP13', label: 'GP13 / SPI1 CS', type: 'spi',     side: 'right' },
    { id: 'GP14', label: 'GP14',           type: 'digital', side: 'right' },
    { id: 'GP15', label: 'GP15',           type: 'digital', side: 'right' },
    { id: 'GP26', label: 'GP26 / ADC0',    type: 'analog',  side: 'right' },
    { id: 'GP27', label: 'GP27 / ADC1',    type: 'analog',  side: 'right' },
    { id: 'GP28', label: 'GP28 / ADC2',    type: 'analog',  side: 'right' },
    { id: '3V3',  label: '3.3V',           type: 'power',   side: 'right' },
    { id: 'VSYS', label: 'VSYS (5V)',      type: 'power',   side: 'right' },
    { id: 'GND',  label: 'GND',            type: 'ground',  side: 'right' },
  ],

  arduino_nano: [
    { id: 'D2',  label: 'D2',         type: 'digital', side: 'left' },
    { id: 'D3',  label: 'D3~',        type: 'pwm',     side: 'left' },
    { id: 'D4',  label: 'D4',         type: 'digital', side: 'left' },
    { id: 'D5',  label: 'D5~',        type: 'pwm',     side: 'left' },
    { id: 'D6',  label: 'D6~',        type: 'pwm',     side: 'left' },
    { id: 'D7',  label: 'D7',         type: 'digital', side: 'left' },
    { id: 'D8',  label: 'D8',         type: 'digital', side: 'left' },
    { id: 'D9',  label: 'D9~',        type: 'pwm',     side: 'left' },
    { id: 'D10', label: 'D10~ / SS',  type: 'spi',     side: 'left' },
    { id: 'D11', label: 'D11 / MOSI', type: 'spi',     side: 'left' },
    { id: 'D12', label: 'D12 / MISO', type: 'spi',     side: 'left' },
    { id: 'D13', label: 'D13 / SCK',  type: 'spi',     side: 'right' },
    { id: 'A0',  label: 'A0',         type: 'analog',  side: 'right' },
    { id: 'A1',  label: 'A1',         type: 'analog',  side: 'right' },
    { id: 'A2',  label: 'A2',         type: 'analog',  side: 'right' },
    { id: 'A3',  label: 'A3',         type: 'analog',  side: 'right' },
    { id: 'A4',  label: 'A4 / SDA',   type: 'i2c',     side: 'right', i2cBus: true },
    { id: 'A5',  label: 'A5 / SCL',   type: 'i2c',     side: 'right', i2cBus: true },
    { id: 'A6',  label: 'A6',         type: 'analog',  side: 'right' },
    { id: 'A7',  label: 'A7',         type: 'analog',  side: 'right' },
    { id: '5V',  label: '5V',         type: 'power',   side: 'right' },
    { id: '3V3', label: '3.3V',       type: 'power',   side: 'right' },
    { id: 'GND', label: 'GND',        type: 'ground',  side: 'right' },
  ],

  stm32f103: [
    { id: 'PA0',  label: 'PA0 / ADC0', type: 'analog',  side: 'left' },
    { id: 'PA1',  label: 'PA1 / ADC1', type: 'analog',  side: 'left' },
    { id: 'PA2',  label: 'PA2 / TX2',  type: 'uart',    side: 'left' },
    { id: 'PA3',  label: 'PA3 / RX2',  type: 'uart',    side: 'left' },
    { id: 'PA4',  label: 'PA4 / SS',   type: 'spi',     side: 'left' },
    { id: 'PA5',  label: 'PA5 / SCK',  type: 'spi',     side: 'left' },
    { id: 'PA6',  label: 'PA6 / MISO', type: 'spi',     side: 'left' },
    { id: 'PA7',  label: 'PA7 / MOSI', type: 'spi',     side: 'left' },
    { id: 'PB6',  label: 'PB6 / SCL',  type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'PB7',  label: 'PB7 / SDA',  type: 'i2c',     side: 'left', i2cBus: true },
    { id: 'PB8',  label: 'PB8',        type: 'digital', side: 'right' },
    { id: 'PB9',  label: 'PB9',        type: 'digital', side: 'right' },
    { id: 'PC13', label: 'PC13 / LED', type: 'digital', side: 'right' },
    { id: '3V3',  label: '3.3V',       type: 'power',   side: 'right' },
    { id: '5V',   label: '5V',         type: 'power',   side: 'right' },
    { id: 'GND',  label: 'GND',        type: 'ground',  side: 'right' },
  ],

  arduino_mega: [
    { id: 'D2',  label: 'D2 / INT4',    type: 'digital', side: 'left' },
    { id: 'D3',  label: 'D3~ / INT5',   type: 'pwm',     side: 'left' },
    { id: 'D4',  label: 'D4~',          type: 'pwm',     side: 'left' },
    { id: 'D5',  label: 'D5~',          type: 'pwm',     side: 'left' },
    { id: 'D6',  label: 'D6~',          type: 'pwm',     side: 'left' },
    { id: 'D7',  label: 'D7',           type: 'digital', side: 'left' },
    { id: 'D8',  label: 'D8~',          type: 'pwm',     side: 'left' },
    { id: 'D9',  label: 'D9~',          type: 'pwm',     side: 'left' },
    { id: 'D10', label: 'D10~',         type: 'pwm',     side: 'left' },
    { id: 'D11', label: 'D11~ / MOSI',  type: 'spi',     side: 'left' },
    { id: 'D12', label: 'D12 / MISO',   type: 'spi',     side: 'left' },
    { id: 'D13', label: 'D13 / SCK',    type: 'spi',     side: 'left' },
    { id: 'D20', label: 'D20 / SDA',    type: 'i2c',     side: 'right', i2cBus: true },
    { id: 'D21', label: 'D21 / SCL',    type: 'i2c',     side: 'right', i2cBus: true },
    { id: 'A0',  label: 'A0',           type: 'analog',  side: 'right' },
    { id: 'A1',  label: 'A1',           type: 'analog',  side: 'right' },
    { id: 'A2',  label: 'A2',           type: 'analog',  side: 'right' },
    { id: 'A3',  label: 'A3',           type: 'analog',  side: 'right' },
    { id: 'A4',  label: 'A4',           type: 'analog',  side: 'right' },
    { id: 'A5',  label: 'A5',           type: 'analog',  side: 'right' },
    { id: '5V',  label: '5V',           type: 'power',   side: 'right' },
    { id: '3V3', label: '3.3V',         type: 'power',   side: 'right' },
    { id: 'GND', label: 'GND',          type: 'ground',  side: 'right' },
  ],
}

// For boards not in BOARD_PIN_MAPS, generate generic pins from interfaces
export function getGenericPins(interfaces: string[]): BoardGpioPin[] {
  const pins: BoardGpioPin[] = []
  const ifaces = interfaces.map(i => i.toLowerCase())

  for (let i = 0; i < 8; i++) {
    pins.push({ id: `GPIO${i}`, label: `GPIO${i}`, type: 'digital', side: i < 4 ? 'left' : 'right' })
  }
  if (ifaces.some(i => i.includes('i2c'))) {
    pins.push({ id: 'SDA', label: 'SDA', type: 'i2c', side: 'left', i2cBus: true })
    pins.push({ id: 'SCL', label: 'SCL', type: 'i2c', side: 'left', i2cBus: true })
  }
  if (ifaces.some(i => i.includes('spi'))) {
    pins.push({ id: 'MOSI', label: 'MOSI', type: 'spi', side: 'left' })
    pins.push({ id: 'MISO', label: 'MISO', type: 'spi', side: 'right' })
    pins.push({ id: 'SCK',  label: 'SCK',  type: 'spi', side: 'right' })
    pins.push({ id: 'CS',   label: 'CS',   type: 'spi', side: 'right' })
  }
  if (ifaces.some(i => i.includes('uart') || i.includes('serial'))) {
    pins.push({ id: 'TX', label: 'TX', type: 'uart', side: 'left' })
    pins.push({ id: 'RX', label: 'RX', type: 'uart', side: 'left' })
  }
  if (ifaces.some(i => i.includes('adc') || i.includes('analog'))) {
    for (let i = 0; i < 4; i++) {
      pins.push({ id: `A${i}`, label: `A${i}`, type: 'analog', side: 'right' })
    }
  }
  pins.push({ id: '3V3', label: '3.3V', type: 'power',  side: 'right' })
  pins.push({ id: '5V',  label: '5V',   type: 'power',  side: 'right' })
  pins.push({ id: 'GND', label: 'GND',  type: 'ground', side: 'right' })
  return pins
}

// ═══════════════════════════════════════════════════════════════════════════════
//  CATEGORY DISPLAY CONFIG
// ═══════════════════════════════════════════════════════════════════════════════

export const CATEGORY_CONFIG: Record<string, { label: string; color: string; bg: string; border: string }> = {
  sensor:        { label: 'Sensors',       color: 'text-amber-400',  bg: 'bg-amber-400/10',  border: 'border-amber-400/30' },
  display:       { label: 'Displays',      color: 'text-blue-400',   bg: 'bg-blue-400/10',   border: 'border-blue-400/30' },
  actuator:      { label: 'Actuators',     color: 'text-green-400',  bg: 'bg-green-400/10',  border: 'border-green-400/30' },
  communication: { label: 'Communication', color: 'text-purple-400', bg: 'bg-purple-400/10', border: 'border-purple-400/30' },
  storage:       { label: 'Storage',       color: 'text-cyan-400',   bg: 'bg-cyan-400/10',   border: 'border-cyan-400/30' },
  audio:         { label: 'Audio',         color: 'text-pink-400',   bg: 'bg-pink-400/10',   border: 'border-pink-400/30' },
  motor:         { label: 'Motors',        color: 'text-red-400',    bg: 'bg-red-400/10',    border: 'border-red-400/30' },
  timing:        { label: 'Timing',        color: 'text-indigo-400', bg: 'bg-indigo-400/10', border: 'border-indigo-400/30' },
  misc:          { label: 'Input / Misc',  color: 'text-zinc-400',   bg: 'bg-zinc-400/10',   border: 'border-zinc-400/30' },
}
